export interface CustomerStory {
    slug: string;
    company: string;
    industry: string;
    metaTitle: string;
    metaDescription: string;
    headline: string;
    companySize: string;
    challenge: string;
    solution: string;
    results: { metric: string; value: string; description: string }[];
    quote: { text: string; author: string; role: string };
}

const cs = (slug: string, company: string, industry: string, size: string, challenge: string, solution: string, results: [string, string, string][], quote: [string, string, string]): CustomerStory => ({
    slug, company, industry, companySize: size,
    metaTitle: `${company} Case Study | Remova`,
    metaDescription: `How ${company} uses Remova for enterprise AI governance. ${results[0][0]}: ${results[0][1]}.`,
    headline: `How ${company} Secured Enterprise AI`,
    challenge, solution,
    results: results.map(([m, v, d]) => ({ metric: m, value: v, description: d })),
    quote: { text: quote[0], author: quote[1], role: quote[2] },
});

export const customerStories: CustomerStory[] = [
    cs("fortune-500-bank", "A Fortune 500 Bank", "Financial Services", "50,000+ employees", "The bank's 12,000 knowledge workers were using personal ChatGPT accounts, creating massive data leak risk with client financial data, account numbers, and trading strategies potentially exposed to third-party AI providers.", "Deployed Remova with on-premises option for the trading floor, cloud for general staff. PII redaction catches financial data automatically. Department budgets control costs across 40+ business units.", [["Shadow AI Reduction", "94%", "Personal AI account usage dropped from 67% to 4% within 60 days of Remova deployment."], ["Data Leak Prevention", "12,000+", "PII instances detected and blocked per month across all departments."], ["Cost Savings", "$2.1M/year", "Consolidated from 8 separate AI subscriptions to one governed platform."], ["Compliance", "100%", "Full SOX and PCI-DSS compliance for all AI interactions with immutable audit trails."]], ["Remova gave us enterprise AI governance without slowing down our teams. The dual-layer guardrails catch things we didn't even know to look for.", "Chief Information Security Officer", "Fortune 500 Bank"]),
    cs("global-law-firm", "A Top 20 Global Law Firm", "Legal", "5,000+ attorneys", "Attorneys needed AI for contract review, legal research, and drafting — but attorney-client privilege made any data persistence unacceptable. Consumer AI tools were explicitly prohibited.", "Remova's zero-history architecture ensures no conversation data is stored server-side. Claude's 200K context window handles large legal documents. Matter-based access controls mirror the firm's conflict management.", [["Productivity Gain", "3.2x", "Attorney research and drafting productivity increased 3.2x with AI assistance."], ["Privilege Protection", "Zero", "Zero instances of client data persistence — verified by external security audit."], ["Adoption Rate", "89%", "89% of attorneys actively using Remova within 90 days of deployment."], ["Cost Control", "$180K/mo", "Predictable monthly AI costs with department budgets replacing ad-hoc subscriptions."]], ["Zero-history architecture isn't just a feature for us — it's a requirement. Remova is the only platform we could deploy without compromising privilege.", "Chief Technology Officer", "Top 20 Global Law Firm"]),
    cs("healthcare-system", "A Regional Healthcare System", "Healthcare", "15,000+ staff", "Clinicians wanted AI for documentation and clinical decision support, but HIPAA compliance required PHI protection at every layer. Previous AI tools failed security review.", "Deployed Remova with automatic PHI detection, zero-history architecture, and BAA. Role-based access ensures clinicians access clinical AI while administrative staff uses operational AI.", [["Documentation Time", "-45%", "Clinical documentation time reduced by 45%, addressing physician burnout."], ["PHI Blocked", "8,500+", "PHI instances automatically detected and blocked per month."], ["HIPAA Compliance", "100%", "Full HIPAA compliance verified by independent third-party audit."], ["Staff Satisfaction", "+62%", "Staff satisfaction with AI tools improved 62% vs. previous solution."]], ["We couldn't find another AI platform that met our HIPAA requirements until Remova. The PHI detection is remarkably accurate.", "Chief Medical Information Officer", "Regional Healthcare System"]),
    cs("tech-unicorn", "A $5B Tech Unicorn", "Technology", "3,000+ employees", "Engineering teams were the heaviest AI users but also the biggest risk — pasting proprietary source code into consumer AI tools. The company needed multi-model access with source code DLP.", "Remova provides 300+ models through one governed interface. Source code DLP patterns detect and block proprietary algorithms, API keys, and internal architecture details. Per-team budgets control engineering AI costs.", [["Models Available", "300+", "Engineers access GPT-4o, Claude, DeepSeek, and Llama through one platform."], ["Code Leaks Prevented", "2,400+", "Proprietary code snippets blocked from reaching AI providers per month."], ["Developer Productivity", "+47%", "Self-reported developer productivity increase with governed AI access."], ["Monthly Savings", "$340K", "Cost optimization through intelligent model routing saved $340K monthly."]], ["Our engineers were going to use AI regardless. Remova let us embrace that while protecting our most valuable IP.", "VP of Engineering", "$5B Tech Unicorn"]),
    cs("insurance-carrier", "A National Insurance Carrier", "Insurance", "8,000+ employees", "Underwriters and claims adjusters needed AI for risk assessment and claims processing, but policyholder PII and proprietary actuarial models required protection.", "Deployed Remova with PII redaction configured for insurance-specific data patterns (policy numbers, claim IDs, actuarial data). Department budgets separate underwriting, claims, and operations.", [["Claims Processing", "-35%", "Claims processing time reduced 35% with AI-assisted analysis."], ["PII Protection", "99.7%", "PII detection accuracy across insurance-specific data patterns."], ["Underwriting Speed", "2.5x", "Underwriting research and risk assessment accelerated 2.5x."], ["ROI", "8.2x", "8.2x return on investment within the first 6 months."]], ["The insurance-specific PII patterns were critical. Generic DLP tools miss policy numbers and claim identifiers that Remova catches.", "Chief Digital Officer", "National Insurance Carrier"]),
    cs("consulting-firm", "A Big Four Consulting Firm", "Professional Services", "100,000+ employees", "Consultants handle extremely sensitive client data across every industry. Each engagement has different confidentiality requirements, making one-size-fits-all AI governance insufficient.", "Remova's department structure maps to practice groups. Per-engagement guardrails enforce client-specific confidentiality. Multi-model access gives specialists the best AI for their domain.", [["Consultant Adoption", "92%", "92% active usage within 120 days across all practice groups."], ["Client Data Protection", "100%", "Zero client data incidents since deployment — verified by internal audit."], ["Productivity Impact", "$45M", "Estimated annual productivity value from AI-assisted consulting delivery."], ["Vendor Consolidation", "12→1", "Consolidated 12 separate AI tools into one governed platform."]], ["We needed AI governance that was as flexible as our consulting engagements. Remova's configurability per department made that possible.", "Global Chief Information Officer", "Big Four Consulting Firm"]),
    cs("defense-contractor", "A Major Defense Contractor", "Defense & Aerospace", "25,000+ employees", "Classified and controlled unclassified information (CUI) requirements demanded air-gapped AI with zero internet connectivity. No cloud AI was acceptable for sensitive programs.", "Deployed Remova on-premises with Llama and Mistral models running on local GPU clusters. Air-gapped architecture ensures no data ever leaves the facility. Security clearance-aligned access controls.", [["Air-Gap Compliance", "100%", "Fully air-gapped deployment with zero external network connectivity."], ["CUI Protection", "Zero Exposure", "Zero incidents of CUI exposure through AI interactions."], ["Analyst Productivity", "+55%", "Intelligence analyst productivity improved 55% with local AI access."], ["Deployment Time", "3 weeks", "Full air-gapped deployment completed in 3 weeks."]], ["Remova is the only platform we found that could run entirely within our classified infrastructure while still providing a modern AI experience.", "Director of Digital Innovation", "Major Defense Contractor"]),
    cs("pharma-company", "A Global Pharmaceutical Company", "Pharmaceutical", "40,000+ employees", "R&D teams needed AI for literature review, data analysis, and regulatory writing, but drug compound data and clinical trial information required maximum protection.", "Remova deployed with FDA-aligned audit trails, automatic detection of compound identifiers and trial data, and department budgets for R&D, regulatory, and commercial teams.", [["Literature Review", "4x faster", "Systematic literature reviews completed 4x faster with AI assistance."], ["Regulatory Writing", "-40%", "Regulatory document drafting time reduced by 40%."], ["IP Protection", "100%", "Zero instances of compound or trial data leakage."], ["FDA Readiness", "Always", "Immutable audit trails always ready for FDA inspection."]], ["AI is transforming pharmaceutical R&D, but we needed governance that understood our regulatory environment. Remova delivers that.", "SVP of R&D Technology", "Global Pharmaceutical Company"]),
    cs("state-government", "A US State Government", "Government", "75,000+ employees", "The state wanted to offer AI to agencies for citizen services, internal operations, and policy analysis, but FedRAMP alignment and citizen data protection were required.", "On-premises Remova deployment within state data centers. Citizen PII detection configured for government data patterns. Agency-based department structure with independent budgets and policies.", [["Agencies Served", "23", "23 state agencies using governed AI through one platform."], ["Citizen Data Protection", "99.9%", "PII detection rate for citizen data patterns."], ["Cost Efficiency", "$2.8M saved", "Saved $2.8M vs. per-agency AI procurement."], ["Employee Satisfaction", "+71%", "Employee satisfaction with technology tools improved 71%."]], ["Deploying AI across 23 agencies with different needs seemed impossible. Remova's department model made it manageable.", "State Chief Information Officer", "US State Government"]),
    cs("private-university", "A Top 30 Private University", "Education", "12,000+ faculty and staff", "Faculty wanted AI for research and teaching, students needed governed access, and the university required FERPA compliance and academic integrity protections.", "Remova deployed with faculty, staff, and student tiers. FERPA-compliant PII protection. Academic integrity policies enforced through guardrails. Research computing integration for data analysis.", [["Faculty Adoption", "78%", "78% of faculty actively using governed AI for research and teaching."], ["FERPA Compliance", "100%", "Full FERPA compliance for all student data interactions."], ["Research Output", "+35%", "Research productivity increased 35% with AI-assisted literature review and analysis."], ["Cost Control", "$92K/mo", "Predictable monthly costs with per-department budgets."]], ["Remova let us embrace AI across the university while maintaining the academic integrity and data privacy standards we require.", "Vice Provost for Digital Learning", "Top 30 Private University"]),
    cs("media-conglomerate", "A Global Media Conglomerate", "Media & Entertainment", "20,000+ employees", "Content teams across news, entertainment, and publishing needed AI for writing, editing, and research, but brand voice consistency and factual accuracy were critical.", "Remova deployed with brand-specific guardrails per media property. Fact-checking guardrails prevent AI hallucinations from reaching published content. Multi-model access optimized by content type.", [["Content Output", "+65%", "Content production volume increased 65% with AI assistance."], ["Brand Compliance", "99.5%", "Brand voice adherence rate across AI-assisted content."], ["Fact-Check Catches", "1,200+", "Factual inaccuracies caught by output guardrails per month."], ["Time to Publish", "-40%", "Average time to publish reduced by 40% with AI workflows."]], ["Each of our media brands has a distinct voice. Remova's per-department guardrails let us govern AI differently for news vs. entertainment.", "Chief Digital Officer", "Global Media Conglomerate"]),
    cs("logistics-giant", "A Fortune 100 Logistics Company", "Transportation & Logistics", "300,000+ employees", "Operations teams needed AI for route optimization, fleet analysis, and customer communication, but competitive logistics data and customer shipment information required protection.", "Remova deployed across operations, sales, customer service, and corporate functions. Logistics-specific DLP patterns for routing data, pricing, and customer shipment details.", [["Operations Efficiency", "+28%", "Operational efficiency improved 28% with AI-assisted planning."], ["Customer Service", "-50%", "Customer query response time reduced by 50% with AI-assisted agents."], ["Data Protection", "100%", "Zero leakage of competitive routing or pricing data."], ["Scale", "45,000", "45,000 active users across global operations."]], ["At our scale, AI governance needs to work for 45,000 users without creating bottlenecks. Remova scales effortlessly.", "Chief Technology Officer", "Fortune 100 Logistics Company"]),
    cs("fintech-startup", "A Series C Fintech Startup", "Fintech", "500 employees", "Fast-growing fintech needed AI across engineering, product, and operations, but SOC 2 and PCI requirements demanded enterprise-grade governance from day one.", "Remova deployed with SSO via Okta, PII redaction for financial data, and per-team budgets. Self-service onboarding meant zero IT overhead for adding new team members.", [["Time to Deploy", "1 day", "Full deployment including SSO integration completed in one day."], ["SOC 2 Ready", "Day 1", "AI governance controls met SOC 2 requirements from day one."], ["Team Adoption", "96%", "96% of employees actively using AI within 2 weeks."], ["Engineering Velocity", "+40%", "Engineering velocity metrics improved 40% with AI coding assistance."]], ["As a fintech, we can't compromise on security. Remova gave us enterprise governance without enterprise complexity.", "CTO & Co-Founder", "Series C Fintech Startup"]),
    cs("energy-company", "A Major Energy Company", "Energy & Utilities", "35,000+ employees", "Engineers and operators needed AI for technical analysis, safety documentation, and regulatory compliance, but critical infrastructure data and environmental monitoring data required strict controls.", "On-premises deployment for operational technology, cloud for corporate functions. Energy-specific DLP patterns for SCADA data, well coordinates, and pipeline specifications.", [["Safety Documentation", "-55%", "Safety report generation time reduced by 55%."], ["Regulatory Compliance", "100%", "Full NERC CIP compliance for AI interactions involving grid data."], ["Engineering Productivity", "+38%", "Engineering analysis productivity increased 38%."], ["Critical Data Protection", "Zero", "Zero incidents of critical infrastructure data exposure."]], ["Our operational technology data requires the highest level of protection. Remova's on-prem deployment was the only option that met our requirements.", "Chief Digital Officer", "Major Energy Company"]),
    cs("retail-chain", "A 500-Store Retail Chain", "Retail", "25,000+ employees", "Merchandising, marketing, and store operations teams all wanted AI, but customer purchase data, pricing strategies, and vendor negotiations required confidentiality.", "Remova deployed with department structures matching retail org: merchandising, marketing, store ops, supply chain. Customer data PII redaction includes loyalty program identifiers.", [["Merchandising Speed", "3x", "Merchandising analysis and planning 3x faster with AI."], ["Marketing Output", "+70%", "Marketing content production increased 70%."], ["Customer Data Safety", "100%", "Zero exposure of customer purchase history or loyalty data."], ["Cost Predictability", "±5%", "AI costs within 5% of budget each month with auto-stop."]], ["Retail moves fast. We needed AI governance that keeps up with our pace without adding friction. Remova nails that balance.", "VP of Technology", "500-Store Retail Chain"]),
    cs("accounting-network", "A Top 10 Accounting Network", "Professional Services", "30,000+ professionals", "Audit, tax, and advisory teams needed AI but each practice had different confidentiality, regulatory, and data handling requirements.", "Deployed with practice-level department isolation. Audit teams get SOX-aligned logging, tax teams get IRS data protection, advisory teams get client-specific guardrails.", [["Audit Efficiency", "+45%", "Audit procedure efficiency improved 45% with AI assistance."], ["Tax Research", "3x faster", "Tax research and memo drafting 3x faster."], ["Client Confidentiality", "100%", "Zero cross-client data exposure with department isolation."], ["Firm-Wide ROI", "6.5x", "6.5x ROI within the first year of deployment."]], ["Each practice group has unique governance needs. Remova's department model lets us configure AI governance at the practice level.", "National Managing Partner — Technology", "Top 10 Accounting Network"]),
    cs("biotech-company", "A Clinical-Stage Biotech", "Biotechnology", "800 employees", "Small biotech with limited IT resources needed enterprise-grade AI governance for clinical data protection without dedicated governance staff.", "Self-service Remova deployment with pre-built healthcare compliance templates. Automatic PHI and compound detection. Zero IT administration overhead with cloud deployment.", [["Setup Time", "2 hours", "Full deployment with HIPAA-compliant configuration in 2 hours."], ["IT Overhead", "Zero", "Zero dedicated IT staff needed for AI governance."], ["R&D Speed", "+50%", "Research literature processing speed increased 50%."], ["Compliance Cost", "-80%", "AI compliance costs 80% lower than building in-house."]], ["We're a biotech, not a tech company. We needed AI governance that just works without a dedicated team. Remova is exactly that.", "Head of IT", "Clinical-Stage Biotech"]),
    cs("multinational-manufacturer", "A Global Manufacturing Corporation", "Manufacturing", "60,000+ employees", "Operations across 15 countries needed governed AI with data sovereignty controls. Different regions had different regulatory requirements for AI usage.", "Multi-region Remova deployment with data sovereignty controls per country. Regional department structures with local compliance policies. Multilingual support for global teams.", [["Countries Deployed", "15", "Governed AI deployed across 15 countries simultaneously."], ["Data Sovereignty", "100%", "Full compliance with local data sovereignty requirements in all regions."], ["Global Adoption", "34,000", "34,000 active users across global manufacturing operations."], ["Process Optimization", "$12M", "$12M annual value from AI-optimized manufacturing processes."]], ["Global deployment with local compliance was our biggest challenge. Remova's data sovereignty controls made it possible.", "Global CIO", "Global Manufacturing Corporation"]),
    cs("investment-bank", "A Bulge Bracket Investment Bank", "Investment Banking", "15,000+ employees", "IBD, trading, and research teams needed AI but deal data, MNPI, and trading strategies required maximum protection with SEC compliance.", "Air-gapped deployment for trading floor, governed cloud for IBD and research. Chinese wall enforcement through department isolation. SEC-compliant audit trails for all AI usage.", [["Deal Efficiency", "+60%", "M&A analysis and pitch preparation 60% faster with AI."], ["MNPI Protection", "100%", "Zero incidents of material non-public information exposure."], ["Trading Floor Safety", "Air-Gapped", "Complete air-gap isolation for trading operations."], ["Compliance Confidence", "100%", "SEC examination readiness with comprehensive audit trails."]], ["In investment banking, a single data leak can be career-ending. Remova's dual deployment model gives us speed and security.", "Chief Technology Officer", "Bulge Bracket Investment Bank"]),
    cs("telecom-operator", "A National Telecom Operator", "Telecommunications", "45,000+ employees", "Customer service, network operations, and enterprise sales all needed AI, but subscriber data protection (CPNI) and network infrastructure security were non-negotiable.", "Remova deployed with CPNI-specific PII patterns, network data DLP rules, and department budgets for customer service, NOC, and enterprise sales.", [["Call Resolution", "-30%", "Average call resolution time decreased 30% with AI-assisted agents."], ["CPNI Compliance", "100%", "Full CPNI compliance across all AI interactions."], ["Network Ops", "+25%", "Network operations efficiency improved 25%."], ["Customer Satisfaction", "+18 NPS", "Net Promoter Score improved 18 points with AI-enhanced service."]], ["Telecom has unique data protection requirements. CPNI compliance isn't optional, and Remova handles it automatically.", "SVP of Technology", "National Telecom Operator"]),
];
