export interface Feature {
    slug: string;
    title: string;
    metaTitle: string;
    metaDescription: string;
    headline: string;
    subheadline: string;
    description: string;
    benefits: string[];
    useCases: string[];
    faqs?: { question: string; answer: string }[];
    lastModified?: string;
}

export const features: Feature[] = [
    {
        slug: "sensitive-data-masking",
        lastModified: "2026-04-26",
        title: "Sensitive Data Masking",
        metaTitle: "Sensitive Data Masking — Keep Confidential Info Out of AI",
        metaDescription: "Automatically detect and mask sensitive data like names, financials, and internal secrets before they ever reach an AI model.",
        headline: "Sensitive Data Masking",
        subheadline: "Your confidential information never leaves your walls",
        description: "When your team uses AI, there's always a risk that someone accidentally pastes a client name, a financial figure, or an internal secret into a prompt. Remova catches that before it happens. It scans every message for sensitive patterns — personal data, account numbers, proprietary terms — and masks them automatically, so the AI still gets useful context without ever seeing the real data.",
        benefits: [
            "Personal data, financial info, and trade secrets are detected and masked in real time",
            "Your team keeps working normally — masking happens silently in the background",
            "Different departments can have different sensitivity levels (e.g. legal vs. marketing)",
            "Every masking event is logged so you can review what was caught and when",
            "Works across all AI models and conversations — no gaps",
        ],
        useCases: [
            "Preventing client names and contract details from reaching AI models",
            "Letting legal teams use AI safely without exposing case-sensitive information",
            "Protecting financial data when finance teams draft reports with AI",
            "Giving HR teams AI access without risking employee data leaks",
        ],
    },
    {
        slug: "ai-safety-controls",
        lastModified: "2026-04-26",
        title: "AI Safety Controls",
        metaTitle: "AI Safety Controls — Set the Rules Before AI Responds",
        metaDescription: "Define what AI can and cannot do across your organization. Block unsafe outputs, warn on risky prompts, and keep AI helpful without being harmful.",
        headline: "AI Safety Controls",
        subheadline: "You decide what AI can and cannot do",
        description: "AI is powerful, but without clear boundaries it can produce content that's off-brand, inappropriate, or outright risky. Remova lets you set straightforward rules: block certain topics entirely, flag borderline requests for review, and let safe work flow through instantly. Your team gets the benefit of AI without the worry.",
        benefits: [
            "Set simple rules like 'never discuss competitor pricing' or 'block medical advice'",
            "Risky prompts get flagged — not just ignored — so nothing slips through",
            "Safe, everyday work goes through instantly with zero friction",
            "Rules apply organization-wide so every team plays by the same playbook",
            "See exactly where and when safety rules are triggered",
        ],
        useCases: [
            "Blocking AI from generating content on restricted topics",
            "Flagging customer-facing outputs for human review before they go out",
            "Applying company-wide content safety standards automatically",
            "Preventing AI from making claims your legal team hasn't approved",
        ],
    },
    {
        slug: "cost-controls",
        lastModified: "2026-04-26",
        title: "Cost Controls",
        metaTitle: "AI Cost Controls — Budget AI Spending by Team",
        metaDescription: "Set spending limits per team and department. Get alerts before budgets run out. Know exactly where every dollar of AI spend goes.",
        headline: "Cost Controls",
        subheadline: "No more surprise AI bills at the end of the month",
        description: "AI usage can get expensive fast — especially when every team starts experimenting. Remova gives you a clear spending dashboard with limits you set per department. You'll get alerts before budgets are used up, and hard caps prevent overspending. No more guessing where the money went.",
        benefits: [
            "Set monthly budgets per department — marketing gets X, engineering gets Y",
            "Get notified at 50%, 80%, and 100% of budget so there are no surprises",
            "See exactly which teams and users are driving costs",
            "Choose between soft warnings and hard spending caps per team",
            "Review spending trends over time to plan ahead",
        ],
        useCases: [
            "Giving each department a fair AI budget without worrying about overspend",
            "Alerting team leads before their monthly AI budget runs out",
            "Tracking which projects and teams generate the most AI costs",
            "Making AI cost planning part of your regular quarterly budgeting",
        ],
    },
    {
        slug: "team-ai-workspaces",
        lastModified: "2026-04-26",
        title: "Team AI Workspaces",
        metaTitle: "Team AI Workspaces — Give Every Department Its Own AI",
        metaDescription: "Set up dedicated AI environments for each team with their own models, rules, and budgets. Everyone gets AI built for their daily work.",
        headline: "Team AI Workspaces",
        subheadline: "Every team gets AI that's built for how they work",
        description: "Not every team needs the same AI setup. Marketing needs creative writing help, legal needs careful summarization, and engineering needs code assistance. Remova lets you create dedicated AI workspaces for each team — with their own approved models, safety rules, and budgets. Teams get AI that actually fits their daily work instead of a one-size-fits-all tool.",
        benefits: [
            "Each department gets its own AI environment with tailored settings",
            "Team leads can manage their own workspace without needing IT every time",
            "The right AI models are available to the right teams — no more, no less",
            "New team members get onboarded into a ready-to-use AI workspace instantly",
            "Central IT keeps oversight while teams stay independent day-to-day",
        ],
        useCases: [
            "Setting up a creative writing AI workspace for marketing with brand guidelines built in",
            "Giving customer support a dedicated AI assistant trained on your help docs",
            "Letting engineering use code-focused AI models without affecting other teams",
            "Rolling out AI to a new department in minutes with pre-configured defaults",
        ],
    },
    {
        slug: "frontier-models-on-prem",
        lastModified: "2026-04-26",
        title: "Frontier Models, On-Prem Safety",
        metaTitle: "Frontier AI Models with On-Prem Safety — Best of Both Worlds",
        metaDescription: "Access the most powerful AI models like GPT-4o, Claude, and Gemini with the safety and control of on-premises deployment.",
        headline: "Frontier Models, On-Prem Safety",
        subheadline: "The world's best AI models with the security your IT team demands",
        description: "You shouldn't have to choose between powerful AI and data security. Remova gives your teams access to frontier models — GPT-4o, Claude, Gemini, and more — while keeping every interaction governed, logged, and protected behind your organization's own safety layer. It's like having the best AI lab in the world inside your own building.",
        benefits: [
            "Access GPT-4o, Claude, Gemini, and other leading models from one platform",
            "Every prompt and response passes through your organization's safety controls",
            "No data leaves your governed environment — models work for you, not the other way around",
            "Switch between models freely without re-building your security setup",
            "New models are available as soon as they launch — with your rules already applied",
        ],
        useCases: [
            "Letting teams use the latest GPT or Claude models without opening security holes",
            "Comparing outputs from different frontier models for critical business decisions",
            "Upgrading to new model releases instantly with existing safety rules intact",
            "Using the best model for each task — code, writing, analysis — from one governed platform",
        ],
    },
    {
        slug: "role-based-access",
        lastModified: "2026-04-26",
        title: "Role-Based Access",
        metaTitle: "Role-Based AI Access — Right People, Right Tools",
        metaDescription: "Control who can use which AI models and features. Simple role assignments that match your org structure.",
        headline: "Role-Based Access",
        subheadline: "Everyone gets the access they need — nothing more, nothing less",
        description: "Not everyone in your company should have the same AI access. Interns probably don't need GPT-4o with full document upload. Remova lets you assign access by role: basic users, power users, team leads, and admins each see exactly what they should. It's as simple as your existing org chart.",
        benefits: [
            "Assign AI access levels that mirror your actual org structure",
            "Team leads manage their own members without involving central IT",
            "Sensitive models and capabilities are reserved for people who need them",
            "Every access change is logged — you always know who has what",
            "New hires get the right access level automatically based on their role",
        ],
        useCases: [
            "Limiting expensive premium models to senior team members",
            "Giving department heads the ability to manage their own team's AI access",
            "Restricting document upload and knowledge base access to authorized roles",
            "Setting up automatic access levels for new employees based on their department",
        ],
    },
    {
        slug: "ready-made-ai-workflows",
        lastModified: "2026-04-26",
        title: "Ready-Made AI Workflows",
        metaTitle: "Ready-Made AI Workflows — Pre-Built AI for Common Tasks",
        metaDescription: "Give your teams pre-configured AI workflows for everyday tasks like drafting emails, summarizing docs, and writing reports — with safety built in.",
        headline: "Ready-Made AI Workflows",
        subheadline: "Pre-built AI tools your team can use from day one",
        description: "Most people don't want to write clever prompts — they just want to get their work done. Remova comes with ready-made workflows for common tasks: email drafting, document summarization, report writing, data analysis, and more. Each workflow has the right model, the right safety rules, and the right output format already configured.",
        benefits: [
            "Your team starts using AI productively from the first day — no training needed",
            "Each workflow uses the best model and settings for that specific task",
            "Safety rules are baked into every workflow — no way to accidentally bypass them",
            "Create custom workflows for your organization's unique needs",
            "Share proven workflows across teams so best practices spread naturally",
        ],
        useCases: [
            "Giving sales a one-click AI tool for drafting proposal emails",
            "Setting up a document summarizer for the legal team with confidentiality rules",
            "Creating a weekly report generator for project managers",
            "Building a customer FAQ assistant for the support team",
        ],
    },
    {
        slug: "company-knowledge-base",
        lastModified: "2026-04-26",
        title: "Company Knowledge Base",
        metaTitle: "Company Knowledge Base — AI That Knows Your Business",
        metaDescription: "Connect your internal documents, policies, and guides so AI answers are grounded in your actual company knowledge — not generic internet data.",
        headline: "Company Knowledge Base",
        subheadline: "AI that answers based on your company's actual knowledge",
        description: "Generic AI doesn't know your company's policies, products, or processes. Remova lets you upload internal documents — handbooks, product specs, SOPs, brand guides — so the AI gives answers based on your real information. It's the difference between a smart intern who just started and one who's read everything.",
        benefits: [
            "AI responses reference your actual internal documents and policies",
            "Different teams can have their own knowledge bases (HR docs for HR, product docs for product)",
            "Access to knowledge bases is controlled — only authorized teams see their docs",
            "Reduces wrong answers by grounding AI in verified, approved sources",
            "Upload new documents anytime and AI starts using them immediately",
        ],
        useCases: [
            "Answering employee policy questions using the actual HR handbook",
            "Helping support teams respond to customers using real product documentation",
            "Onboarding new hires with AI that knows company processes and culture",
            "Letting teams ask questions about internal SOPs without hunting through shared drives",
        ],
    },
    {
        slug: "full-audit-trail",
        lastModified: "2026-04-26",
        title: "Full Audit Trail",
        metaTitle: "Full AI Audit Trail — See Everything That Happens",
        metaDescription: "Every AI interaction, safety event, and admin action is logged. Complete visibility for compliance, reviews, and peace of mind.",
        headline: "Full Audit Trail",
        subheadline: "Every AI interaction is logged — nothing goes unnoticed",
        description: "When the board asks 'how is AI being used here?', you need a real answer. Remova logs every interaction: who used AI, what they asked, which safety rules were triggered, and what the AI responded. It's not about surveillance — it's about having the evidence when you need it for compliance reviews, incident investigations, or simply understanding how your teams use AI.",
        benefits: [
            "Complete record of every AI conversation, prompt, and response",
            "Safety and masking events are logged with full context",
            "Admin actions (rule changes, access updates) are tracked too",
            "Export logs anytime for compliance reports or internal reviews",
            "Search and filter by user, team, date, or event type",
        ],
        useCases: [
            "Preparing for compliance audits with complete AI usage records",
            "Investigating a specific AI interaction when something goes wrong",
            "Reporting AI usage patterns to leadership on a monthly basis",
            "Proving to regulators that your AI usage is governed and documented",
        ],
    },
    {
        slug: "usage-dashboard",
        lastModified: "2026-04-26",
        title: "Usage Dashboard",
        metaTitle: "AI Usage Dashboard — Real-Time Insights at a Glance",
        metaDescription: "See who's using AI, how much it costs, and where safety rules kick in — all in one clean dashboard.",
        headline: "Usage Dashboard",
        subheadline: "One dashboard to see everything about your AI usage",
        description: "You can't manage what you can't see. Remova's dashboard shows you exactly how AI is being used across your organization — which teams are active, what it's costing, how many safety events occurred, and where adoption is growing or stalling. It's the single pane of glass every IT leader and CFO has been asking for.",
        benefits: [
            "See adoption, costs, and safety events in one place — no spreadsheet gymnastics",
            "Break down usage by team, department, or individual",
            "Track trends over time to spot patterns and plan ahead",
            "Real-time data, not last-month's report",
            "Share dashboard views with leadership without manual report building",
        ],
        useCases: [
            "Monthly reporting to the C-suite on AI adoption and spend",
            "Identifying which teams are getting real value from AI vs. barely using it",
            "Catching unusual usage patterns that might indicate misuse",
            "Planning next quarter's AI budget based on actual usage data",
        ],
    },
    {
        slug: "data-retention-controls",
        lastModified: "2026-04-26",
        title: "Data Retention Controls",
        metaTitle: "AI Data Retention Controls — You Decide What's Kept",
        metaDescription: "Control how long AI conversation data is stored, who can see it, and when it's deleted. Your data, your rules.",
        headline: "Data Retention Controls",
        subheadline: "You decide how long AI data is stored — and when it's deleted",
        description: "Not every AI conversation needs to live forever. Remova lets you set retention rules: keep data for 30 days, 90 days, or a custom period. Some teams might need longer retention for compliance, others want conversations deleted as soon as they're done. You set the policy, Remova enforces it automatically.",
        benefits: [
            "Set different retention periods for different teams or sensitivity levels",
            "Automatic deletion when retention periods expire — no manual cleanup",
            "Meet data privacy regulations (GDPR, internal policies) without extra effort",
            "Choose who can access stored conversations and for how long",
            "Clear reporting on what data is being retained and what's been purged",
        ],
        useCases: [
            "Auto-deleting AI conversations after 30 days for general teams",
            "Keeping legal and compliance AI interactions for longer audit periods",
            "Meeting GDPR data minimization requirements automatically",
            "Giving employees transparency about how their AI usage data is handled",
        ],
    },
    {
        slug: "governed-api-access",
        lastModified: "2026-04-26",
        title: "Governed API Access",
        metaTitle: "Governed API Access — AI in Your Own Apps, With Rules",
        metaDescription: "Embed governed AI capabilities into your internal tools and apps. Same safety rules, same cost controls, same audit trail.",
        headline: "Governed API Access",
        subheadline: "Build AI into your own apps — with all the safety built in",
        description: "Your developers want to add AI to internal tools — that's great. But if they connect directly to OpenAI or Anthropic, they bypass every safety rule you've set up. Remova's API lets your developers build AI into any internal app while keeping the same safety controls, cost limits, and audit trails that apply everywhere else.",
        benefits: [
            "Your internal apps get AI with the same rules as the main platform",
            "Developers get a clean API — easy to integrate, impossible to bypass",
            "Every API call is tracked in the same dashboard as regular usage",
            "Cost controls apply to API usage too — no hidden bills from internal tools",
            "Ship AI features in your products faster without rebuilding governance from scratch",
        ],
        useCases: [
            "Adding an AI assistant to your internal CRM that follows company data rules",
            "Building smart search into your intranet with governed AI behind it",
            "Automating repetitive workflows with AI while keeping audit trails intact",
            "Letting your product team prototype AI features without creating security risks",
        ],
    },
];
