export interface Feature {
    slug: string;
    title: string;
    metaTitle: string;
    metaDescription: string;
    headline: string;
    subheadline: string;
    description: string;
    benefits: string[];
    useCases: string[];
    faqs?: { question: string; answer: string }[];
    lastModified?: string;
}

export const features: Feature[] = [
    {
        slug: "policy-guardrails",
        lastModified: "2026-04-23",
        title: "Policy Guardrails",
        metaTitle: "Policy Guardrails for Enterprise AI | Remova",
        metaDescription: "Apply policy checks to AI inputs and outputs with configurable enforcement and audit visibility.",
        headline: "Policy Guardrails",
        subheadline: "Enforce policy before risky output reaches users",
        description: "Remova evaluates AI requests and responses against organization policy (a critical component for <a href='/blog/governing-agentic-ai-enterprise'>governing agentic AI</a>) so teams can block unsafe behavior, warn on borderline cases, and keep legitimate work moving without relying on manual spot checks.",
        benefits: [
            "Configurable rules tied to actual workflow policy",
            "Checks on both prompts and generated output",
            "Allow, block, warn, and review actions based on severity",
            "Centralized administration instead of team-by-team drift",
            "Audit visibility into where policy is being triggered",
        ],
        useCases: [
            "Blocking restricted topics for specific departments",
            "Requiring stricter controls for customer-facing content",
            "Applying organization-wide safety baselines",
            "Reducing policy drift across teams",
        ],
    },
    {
        slug: "sensitive-data-protection",
        lastModified: "2026-04-23",
        title: "Sensitive Data Protection",
        metaTitle: "Sensitive Data Protection for Enterprise AI | Remova",
        metaDescription: "Detect and protect sensitive information in AI workflows with configurable controls and event logging.",
        headline: "Sensitive Data Protection",
        subheadline: "Reduce accidental data exposure in AI usage",
        description: "Remova helps identify sensitive content in prompts and responses (essential for protecting <a href='/blog/sensitive-data-protection-ai-workflows'>data in enterprise AI workflows</a> and mitigating <a href='/blog/shadow-ai-enterprise-detection-response'>shadow AI</a>) so organizations can redact, block, or review risky interactions before confidential material moves beyond approved boundaries.",
        benefits: [
            "Pattern and context-aware detection for higher-risk content",
            "Configurable redaction, blocking, and escalation behavior",
            "Department-specific protection profiles by workflow risk",
            "Event logging that supports review and incident follow-up",
            "Policy-aligned handling of confidential business information",
        ],
        useCases: [
            "Preventing confidential data from entering model prompts",
            "Masking sensitive fields in team workflows",
            "Applying stricter controls in legal and finance",
            "Reviewing data protection events by department",
        ],
    },
    {
        slug: "role-access-control",
        title: "Role-Based Access Control",
        metaTitle: "Role-Based Access Control for AI | Remova",
        metaDescription: "Manage AI access by role and team with scoped permissions and administrative oversight.",
        headline: "Role-Based Access Control",
        subheadline: "Give teams only the access they need",
        description: "Remova supports role-scoped permissions so administrators can align model access, settings authority, and governance actions with real organizational responsibilities instead of broad shared access.",
        benefits: [
            "Role-scoped permissions for users, admins, and reviewers",
            "Team-level administrative boundaries that reflect ownership",
            "Reduced over-permissioning in high-impact settings",
            "Centralized access governance with local delegation",
            "Clear ownership of who changed what and why",
        ],
        useCases: [
            "Delegating team setup to department leads",
            "Restricting high-impact settings to admins",
            "Separating operational and governance responsibilities",
            "Improving access review workflows",
        ],
    },
    {
        slug: "department-budgets",
        title: "Department Budget Controls",
        metaTitle: "Department Budget Controls for AI | Remova",
        metaDescription: "Set spending limits, alerts, and controls for AI usage by team and department.",
        headline: "Department Budget Controls",
        subheadline: "Keep AI costs predictable across teams",
        description: "Remova provides budget controls for departments and teams so organizations can assign spend ownership, set enforcement thresholds, and prevent AI adoption from turning into uncontrolled monthly variance.",
        benefits: [
            "Department-level allocations with visible ownership",
            "Warning thresholds that surface issues before overrun",
            "Hard and soft limit options by business need",
            "Usage visibility by team, not just total account spend",
            "Clearer cost accountability during expansion",
        ],
        useCases: [
            "Setting separate limits for business units",
            "Alerting managers before budgets are exhausted",
            "Preventing uncontrolled spend in pilot programs",
            "Improving quarterly AI budget planning",
        ],
    },
    {
        slug: "usage-analytics",
        title: "Usage Analytics",
        metaTitle: "Enterprise AI Usage Analytics | Remova",
        metaDescription: "Track AI adoption, policy events, and spend trends with role-appropriate analytics views.",
        headline: "Usage Analytics",
        subheadline: "Understand adoption, risk, and cost in one place",
        description: "Remova provides analytics views for operational and governance teams to monitor usage trends, control effectiveness, exception volume, and spend patterns in one reporting surface.",
        benefits: [
            "Adoption and activity tracking by team and workflow",
            "Policy, safety, and exception event reporting",
            "Spend trend visibility with department context",
            "Breakdowns that support manager and leadership review",
            "Exportable reporting views for recurring governance cadence",
        ],
        useCases: [
            "Monthly executive reporting",
            "Identifying high-risk usage patterns",
            "Tracking governance program adoption",
            "Reviewing spend and policy outcomes together",
        ],
    },
    {
        slug: "preset-workflows",
        title: "Preset Workflows",
        metaTitle: "AI Preset Workflows for Teams | Remova",
        metaDescription: "Create reusable AI presets with approved behavior, controls, and team-level governance defaults.",
        headline: "Preset Workflows",
        subheadline: "Standardize common AI tasks safely",
        description: "Remova lets teams package repeatable AI workflows with governance settings so users can move faster with approved defaults instead of reinventing prompts, permissions, and review steps each time.",
        benefits: [
            "Reusable workflow presets for high-frequency tasks",
            "Governance defaults that travel with each preset",
            "Reduced prompt inconsistency across teams",
            "Faster onboarding for new users and new departments",
            "Centralized lifecycle management for approved workflows",
        ],
        useCases: [
            "Standardizing proposal drafting workflows",
            "Creating approved internal research assistants",
            "Launching role-specific team helpers",
            "Reducing variability in common tasks",
        ],
    },
    {
        slug: "knowledge-grounding",
        title: "Knowledge Grounding",
        metaTitle: "Knowledge Grounding for Enterprise AI | Remova",
        metaDescription: "Ground AI responses on approved organizational knowledge with scoped access and control.",
        headline: "Knowledge Grounding",
        subheadline: "Anchor responses in approved internal context",
        description: "Remova supports organization knowledge grounding so teams can improve response relevance while keeping internal context aligned to access rules, approved sources, and governance expectations.",
        benefits: [
            "Knowledge ingestion tied to approved internal sources",
            "Scoped access to internal context by role or team",
            "Improved response relevance for operational questions",
            "Support for document-heavy internal workflows",
            "Governed use of internal references instead of open retrieval",
        ],
        useCases: [
            "Answering policy questions from internal docs",
            "Supporting onboarding with company context",
            "Grounding support responses on approved sources",
            "Reducing unsupported answers in operational workflows",
        ],
    },
    {
        slug: "audit-trails",
        title: "Audit Trails",
        metaTitle: "AI Audit Trails and Activity Logging | Remova",
        metaDescription: "Maintain traceable records of AI usage and governance actions for review and compliance workflows.",
        headline: "Audit Trails",
        subheadline: "Maintain traceable records of AI activity",
        description: "Remova records key governance and usage events so organizations can investigate incidents, review exception history, and support reporting without stitching evidence together from multiple disconnected systems.",
        benefits: [
            "Traceable activity records across user and admin actions",
            "Governance event logging with operational context",
            "Administrative action visibility for change review",
            "Support for investigation, reporting, and follow-up",
            "Export-friendly audit data for internal evidence needs",
        ],
        useCases: [
            "Preparing internal audit evidence",
            "Investigating policy events",
            "Reviewing admin-level configuration changes",
            "Supporting governance committee reporting",
        ],
    },
    {
        slug: "retention-controls",
        title: "Retention Controls",
        metaTitle: "AI Retention Controls for Enterprise Teams | Remova",
        metaDescription: "Configure retention behavior and access scope for AI interaction data based on organizational policy.",
        headline: "Retention Controls",
        subheadline: "Align data handling with your policy",
        description: "Remova provides configurable retention and access controls so organizations can decide how long AI interaction data persists, who can see it, and how storage behavior matches internal and legal policy requirements.",
        benefits: [
            "Configurable retention settings by workflow sensitivity",
            "Role-scoped access to stored interaction data",
            "Policy-aligned handling of prompts, outputs, and logs",
            "Reduced unnecessary persistence of sensitive content",
            "Support for review and governance validation",
        ],
        useCases: [
            "Applying stricter retention rules to sensitive teams",
            "Limiting data visibility by role",
            "Supporting internal data minimization goals",
            "Maintaining consistent retention posture across departments",
        ],
    },
    {
        slug: "model-governance",
        title: "Model Governance",
        metaTitle: "Model Governance Controls for Enterprise AI | Remova",
        metaDescription: "Control model availability and usage policy by department with centralized governance.",
        headline: "Model Governance",
        subheadline: "Control who can use which model profiles",
        description: "Remova helps organizations govern model access by team and policy posture so new model capabilities can roll out deliberately instead of appearing everywhere by default.",
        benefits: [
            "Department-level control over model availability",
            "Policy-aligned access to premium or higher-risk models",
            "Safer rollout of new model options in phases",
            "Centralized governance of model selection decisions",
            "Consistent user experience by team and role",
        ],
        useCases: [
            "Limiting high-risk profiles to approved teams",
            "Rolling out new model options in phases",
            "Maintaining approved model sets by department",
            "Reducing ad hoc model usage",
        ],
    },
    {
        slug: "api-access",
        title: "Governed API Access",
        metaTitle: "Governed API Access for AI Workflows | Remova",
        metaDescription: "Integrate governed AI usage into internal applications through scoped API access and policy enforcement.",
        headline: "Governed API Access",
        subheadline: "Embed governance into your internal tools",
        description: "Remova exposes API access with governance controls so teams can integrate AI into products, automations, and internal tools without bypassing the same policies used in the main user interface.",
        benefits: [
            "Scoped API access with explicit ownership boundaries",
            "Policy checks on programmatic as well as interactive usage",
            "Usage visibility for API-driven workflows and automations",
            "Consistent governance across UI and API surfaces",
            "Support for internal automation without shadow bypasses",
        ],
        useCases: [
            "Adding governed AI features to internal apps",
            "Automating policy-safe workflow steps",
            "Tracking API-driven usage by team",
            "Keeping governance consistent outside chat interfaces",
        ],
    },
    {
        slug: "onboarding-controls",
        title: "Onboarding Controls",
        metaTitle: "Enterprise AI Onboarding Controls | Remova",
        metaDescription: "Guide setup for teams, access, budgets, and policy defaults through a governed onboarding flow.",
        headline: "Onboarding Controls",
        subheadline: "Launch teams with governance defaults from day one",
        description: "Remova streamlines onboarding so organizations can configure access, budgets, policy baselines, and team ownership early instead of retrofitting controls after risky behavior is already normalized.",
        benefits: [
            "Structured onboarding flow for teams and departments",
            "Early setup of policy, access, and budget baselines",
            "Support for team ownership and configuration handoff",
            "Faster rollout without losing governance discipline",
            "Reduced operational rework after launch",
        ],
        useCases: [
            "Launching a governed pilot quickly",
            "Rolling out new departments with standard controls",
            "Reducing manual setup overhead",
            "Starting with consistent policy defaults",
        ],
    },
];
