export interface Feature {
    slug: string;
    title: string;
    metaTitle: string;
    metaDescription: string;
    headline: string;
    subheadline: string;
    description: string;
    benefits: string[];
    useCases: string[];
    faqs?: { question: string; answer: string }[];
}

export const features: Feature[] = [
    {
        slug: "policy-guardrails",
        title: "Policy Guardrails",
        metaTitle: "Policy Guardrails for Enterprise AI | Remova",
        metaDescription: "Apply policy checks to AI inputs and outputs with configurable enforcement and audit visibility.",
        headline: "Policy Guardrails",
        subheadline: "Enforce policy before risky output reaches users",
        description: "Remova evaluates AI requests and responses against organization policy so teams can reduce unsafe usage while keeping productive workflows moving.",
        benefits: [
            "Configurable policy rules",
            "Input and output checks",
            "Flexible allow, block, and review actions",
            "Centralized policy administration",
            "Audit visibility for policy events",
        ],
        useCases: [
            "Blocking restricted topics for specific departments",
            "Requiring stricter controls for customer-facing content",
            "Applying organization-wide safety baselines",
            "Reducing policy drift across teams",
        ],
    },
    {
        slug: "sensitive-data-protection",
        title: "Sensitive Data Protection",
        metaTitle: "Sensitive Data Protection for Enterprise AI | Remova",
        metaDescription: "Detect and protect sensitive information in AI workflows with configurable controls and event logging.",
        headline: "Sensitive Data Protection",
        subheadline: "Reduce accidental data exposure in AI usage",
        description: "Remova helps identify sensitive content in prompts and responses so organizations can apply consistent protection controls before data leaves approved boundaries.",
        benefits: [
            "Pattern and context-aware detection",
            "Configurable redaction and blocking",
            "Department-specific protection profiles",
            "Event logging for review workflows",
            "Support for internal data handling policy",
        ],
        useCases: [
            "Preventing confidential data from entering model prompts",
            "Masking sensitive fields in team workflows",
            "Applying stricter controls in legal and finance",
            "Reviewing data protection events by department",
        ],
    },
    {
        slug: "role-access-control",
        title: "Role-Based Access Control",
        metaTitle: "Role-Based Access Control for AI | Remova",
        metaDescription: "Manage AI access by role and team with scoped permissions and administrative oversight.",
        headline: "Role-Based Access Control",
        subheadline: "Give teams only the access they need",
        description: "Remova supports role-scoped permissions so administrators can align AI access with organizational responsibilities and governance requirements.",
        benefits: [
            "Role-scoped permissions",
            "Team-level administrative boundaries",
            "Reduced over-permissioning risk",
            "Centralized access governance",
            "Clear ownership of administrative actions",
        ],
        useCases: [
            "Delegating team setup to department leads",
            "Restricting high-impact settings to admins",
            "Separating operational and governance responsibilities",
            "Improving access review workflows",
        ],
    },
    {
        slug: "department-budgets",
        title: "Department Budget Controls",
        metaTitle: "Department Budget Controls for AI | Remova",
        metaDescription: "Set spending limits, alerts, and controls for AI usage by team and department.",
        headline: "Department Budget Controls",
        subheadline: "Keep AI costs predictable across teams",
        description: "Remova provides budget controls for departments and teams so organizations can monitor spend, set limits, and reduce billing surprises.",
        benefits: [
            "Department-level allocations",
            "Configurable warning thresholds",
            "Hard and soft limit options",
            "Usage visibility by team",
            "Support for cost accountability",
        ],
        useCases: [
            "Setting separate limits for business units",
            "Alerting managers before budgets are exhausted",
            "Preventing uncontrolled spend in pilot programs",
            "Improving quarterly AI budget planning",
        ],
    },
    {
        slug: "usage-analytics",
        title: "Usage Analytics",
        metaTitle: "Enterprise AI Usage Analytics | Remova",
        metaDescription: "Track AI adoption, policy events, and spend trends with role-appropriate analytics views.",
        headline: "Usage Analytics",
        subheadline: "Understand adoption, risk, and cost in one place",
        description: "Remova provides analytics views for operational and governance teams to monitor usage trends, control effectiveness, and spend patterns.",
        benefits: [
            "Adoption and activity tracking",
            "Policy and safety event reporting",
            "Spend trend visibility",
            "Department-level breakdowns",
            "Exportable reporting views",
        ],
        useCases: [
            "Monthly executive reporting",
            "Identifying high-risk usage patterns",
            "Tracking governance program adoption",
            "Reviewing spend and policy outcomes together",
        ],
    },
    {
        slug: "preset-workflows",
        title: "Preset Workflows",
        metaTitle: "AI Preset Workflows for Teams | Remova",
        metaDescription: "Create reusable AI presets with approved behavior, controls, and team-level governance defaults.",
        headline: "Preset Workflows",
        subheadline: "Standardize common AI tasks safely",
        description: "Remova lets teams package repeatable AI workflows with governance settings so users can work faster with approved defaults.",
        benefits: [
            "Reusable workflow presets",
            "Governance defaults by team",
            "Reduced prompt inconsistency",
            "Faster onboarding for new users",
            "Centralized preset lifecycle management",
        ],
        useCases: [
            "Standardizing proposal drafting workflows",
            "Creating approved internal research assistants",
            "Launching role-specific team helpers",
            "Reducing variability in common tasks",
        ],
    },
    {
        slug: "knowledge-grounding",
        title: "Knowledge Grounding",
        metaTitle: "Knowledge Grounding for Enterprise AI | Remova",
        metaDescription: "Ground AI responses on approved organizational knowledge with scoped access and control.",
        headline: "Knowledge Grounding",
        subheadline: "Anchor responses in approved internal context",
        description: "Remova supports organization knowledge grounding so teams can improve response relevance while maintaining access boundaries.",
        benefits: [
            "Organization knowledge ingestion",
            "Scoped access to internal context",
            "Improved response relevance",
            "Support for document-based workflows",
            "Governed use of internal references",
        ],
        useCases: [
            "Answering policy questions from internal docs",
            "Supporting onboarding with company context",
            "Grounding support responses on approved sources",
            "Reducing unsupported answers in operational workflows",
        ],
    },
    {
        slug: "audit-trails",
        title: "Audit Trails",
        metaTitle: "AI Audit Trails and Activity Logging | Remova",
        metaDescription: "Maintain traceable records of AI usage and governance actions for review and compliance workflows.",
        headline: "Audit Trails",
        subheadline: "Maintain traceable records of AI activity",
        description: "Remova records key governance and usage events so organizations can support internal review, incident response, and reporting needs.",
        benefits: [
            "Traceable activity records",
            "Governance event logging",
            "Administrative action visibility",
            "Support for review and investigation",
            "Export-friendly audit data",
        ],
        useCases: [
            "Preparing internal audit evidence",
            "Investigating policy events",
            "Reviewing admin-level configuration changes",
            "Supporting governance committee reporting",
        ],
    },
    {
        slug: "retention-controls",
        title: "Retention Controls",
        metaTitle: "AI Retention Controls for Enterprise Teams | Remova",
        metaDescription: "Configure retention behavior and access scope for AI interaction data based on organizational policy.",
        headline: "Retention Controls",
        subheadline: "Align data handling with your policy",
        description: "Remova provides configurable retention and access controls so organizations can align AI data handling with legal and internal policy requirements.",
        benefits: [
            "Configurable retention settings",
            "Role-scoped data access",
            "Policy-aligned data handling",
            "Reduced unnecessary persistence",
            "Support for governance reviews",
        ],
        useCases: [
            "Applying stricter retention rules to sensitive teams",
            "Limiting data visibility by role",
            "Supporting internal data minimization goals",
            "Maintaining consistent retention posture across departments",
        ],
    },
    {
        slug: "model-governance",
        title: "Model Governance",
        metaTitle: "Model Governance Controls for Enterprise AI | Remova",
        metaDescription: "Control model availability and usage policy by department with centralized governance.",
        headline: "Model Governance",
        subheadline: "Control who can use which model profiles",
        description: "Remova helps organizations govern model access by team and policy posture so deployment stays controlled as usage scales.",
        benefits: [
            "Department-level model access control",
            "Policy-aligned model availability",
            "Safer rollout of new model options",
            "Centralized governance of model selection",
            "Consistent user experience by team",
        ],
        useCases: [
            "Limiting high-risk profiles to approved teams",
            "Rolling out new model options in phases",
            "Maintaining approved model sets by department",
            "Reducing ad hoc model usage",
        ],
    },
    {
        slug: "api-access",
        title: "Governed API Access",
        metaTitle: "Governed API Access for AI Workflows | Remova",
        metaDescription: "Integrate governed AI usage into internal applications through scoped API access and policy enforcement.",
        headline: "Governed API Access",
        subheadline: "Embed governance into your internal tools",
        description: "Remova exposes API access with governance controls so teams can integrate AI into products and workflows without bypassing policy.",
        benefits: [
            "Scoped API access",
            "Policy checks on programmatic usage",
            "Usage visibility for API-driven workflows",
            "Consistent governance across UI and API",
            "Support for internal automation",
        ],
        useCases: [
            "Adding governed AI features to internal apps",
            "Automating policy-safe workflow steps",
            "Tracking API-driven usage by team",
            "Keeping governance consistent outside chat interfaces",
        ],
    },
    {
        slug: "onboarding-controls",
        title: "Onboarding Controls",
        metaTitle: "Enterprise AI Onboarding Controls | Remova",
        metaDescription: "Guide setup for teams, access, budgets, and policy defaults through a governed onboarding flow.",
        headline: "Onboarding Controls",
        subheadline: "Launch teams with governance defaults from day one",
        description: "Remova streamlines onboarding so organizations can configure access, budgets, and policy baselines early instead of after risk appears.",
        benefits: [
            "Structured onboarding flow",
            "Early policy baseline setup",
            "Team and access configuration support",
            "Faster controlled rollout",
            "Reduced operational rework",
        ],
        useCases: [
            "Launching a governed pilot quickly",
            "Rolling out new departments with standard controls",
            "Reducing manual setup overhead",
            "Starting with consistent policy defaults",
        ],
    },
];
