export interface Integration {
    slug: string;
    name: string;
    category: "ai-provider" | "identity" | "cloud" | "productivity" | "security" | "dev-tools";
    metaTitle: string;
    metaDescription: string;
    headline: string;
    description: string;
    capabilities: string[];
    setupSteps: string[];
}

const ig = (slug: string, name: string, category: Integration["category"], description: string, capabilities: string[], setupSteps: string[]): Integration => ({
    slug, name, category,
    metaTitle: `${name} Integration | Remova`,
    metaDescription: `Integrate Remova with ${name}. ${capabilities[0]}. Enterprise AI governance for your ${name} deployment.`,
    headline: `${name} Integration`,
    description, capabilities, setupSteps,
});

export const integrations: Integration[] = [
    // AI Providers (12)
    ig("openai", "OpenAI (GPT-4o)", "ai-provider", "Access all OpenAI models including GPT-4o, GPT-4 Turbo, and o1 through Remova's governed gateway. Get enterprise-grade PII redaction, cost controls, and dual-layer guardrails on every OpenAI interaction.", ["GPT-4o, GPT-4 Turbo, o1, and GPT-3.5 access", "Per-department cost controls for OpenAI usage", "PII redaction before prompts reach OpenAI", "Automatic failover to alternative providers", "Usage analytics per model variant"], ["Connect your OpenAI API key or use Remova's managed access", "Configure department-level budget caps for OpenAI models", "Set up PII redaction rules for your organization", "Deploy to your team with SSO"]),
    ig("anthropic", "Anthropic (Claude)", "ai-provider", "Access Claude 3.5 Sonnet, Claude 3 Opus, and Claude 3 Haiku through Remova's governance layer. Get the full Claude experience with enterprise guardrails, cost controls, and zero-history architecture.", ["Claude 3.5 Sonnet, Opus, and Haiku access", "200K context window with governed usage", "Cost tracking per Claude model variant", "PII redaction before prompts reach Anthropic", "Dual-layer guardrails on all Claude interactions"], ["Connect your Anthropic API key or use managed access", "Configure model access per department", "Set budget limits for Claude usage", "Enable PII redaction and guardrails"]),
    ig("google-gemini", "Google Gemini", "ai-provider", "Access Gemini 2.0 Flash, Gemini Pro, and Gemini Ultra through Remova. Enterprise governance for Google's most capable AI models.", ["Gemini 2.0 Flash, Pro, and Ultra access", "Web search integration with governance", "Multi-modal capabilities with guardrails", "Cost normalization across Google models", "Automatic model version management"], ["Add Google AI API credentials", "Configure Gemini model access per team", "Set up content safety guardrails", "Monitor usage and costs"]),
    ig("meta-llama", "Meta Llama", "ai-provider", "Deploy Llama 3.1 models through Remova — including on-premises for maximum data privacy. Open-source AI with enterprise governance.", ["Llama 3.1 405B, 70B, and 8B access", "On-premises deployment option", "Air-gapped support for sensitive environments", "Cost-effective high-performance AI", "Full source code transparency"], ["Choose cloud or on-premises deployment", "Select Llama model variants for your needs", "Configure guardrails and PII redaction", "Deploy with zero-data-outbound assurance"]),
    ig("mistral", "Mistral AI", "ai-provider", "Access Mistral Large, Medium, and open-source models through Remova's governed platform. European AI with enterprise governance.", ["Mistral Large, Medium, and Small access", "EU data residency compliance", "Multilingual capabilities with guardrails", "Cost-effective alternatives to GPT-4", "On-premises deployment available"], ["Connect Mistral API credentials", "Configure model access and budgets", "Enable EU-compliant data handling", "Deploy with guardrails enabled"]),
    ig("cohere", "Cohere", "ai-provider", "Access Cohere's Command and Embed models through Remova. Enterprise-grade RAG and generation with governance controls.", ["Command R+ and Command R access", "Embed models for RAG pipelines", "Multilingual generation with guardrails", "Enterprise-focused AI with added governance", "Cost tracking and optimization"], ["Add Cohere API credentials", "Configure model access per department", "Set up RAG with governance controls", "Monitor usage and costs"]),
    ig("aws-bedrock", "Amazon Bedrock", "ai-provider", "Access Amazon Bedrock's multi-model catalog through Remova for unified governance across Claude, Llama, Mistral, and more on AWS.", ["Multi-model access via Bedrock", "AWS infrastructure integration", "Cross-model governance policies", "Unified cost tracking across Bedrock models", "AWS IAM integration"], ["Connect AWS Bedrock credentials", "Select models from the Bedrock catalog", "Apply unified governance policies", "Track costs across all Bedrock models"]),
    ig("azure-openai", "Azure OpenAI Service", "ai-provider", "Access GPT models through Azure with Remova's additional governance layer. Enterprise controls beyond what Azure provides natively.", ["Azure-hosted GPT-4o and GPT-4 Turbo", "Azure compliance + Remova governance", "Department-level cost controls", "PII redaction before Azure processing", "Hybrid cloud governance"], ["Connect Azure OpenAI Service endpoint", "Layer Remova governance on Azure models", "Configure department budgets", "Enable dual-layer guardrails"]),
    ig("perplexity", "Perplexity AI", "ai-provider", "Access Perplexity's research-focused AI through Remova with enterprise governance, cost controls, and data protection.", ["Perplexity Online models for web research", "Citation-backed answers with governance", "Cost controls on research queries", "PII protection for research prompts", "Usage tracking and analytics"], ["Add Perplexity API access", "Configure research model access", "Set cost limits for research usage", "Enable PII redaction"]),
    ig("deepseek", "DeepSeek", "ai-provider", "Access DeepSeek's cost-effective AI models through Remova. Strong coding and reasoning capabilities with enterprise governance.", ["DeepSeek V3 and R1 access", "Cost-effective coding AI", "Strong reasoning with guardrails", "On-premises deployment available", "Budget-friendly enterprise AI"], ["Connect DeepSeek API credentials", "Configure model access and budgets", "Enable code security guardrails", "Monitor usage and costs"]),
    ig("together-ai", "Together AI", "ai-provider", "Access open-source models through Together AI's infrastructure with Remova governance. Fast inference with enterprise controls.", ["100+ open-source model access", "Fast inference speeds", "Cost-effective model hosting", "Enterprise governance on open models", "Auto-scaling with budget controls"], ["Connect Together AI API key", "Select models for your deployment", "Configure governance policies", "Set budget caps and alerts"]),
    ig("groq", "Groq", "ai-provider", "Access Groq's ultra-fast inference for Llama, Mixtral, and other models through Remova. Lightning speed with enterprise governance.", ["Ultra-fast LPU inference", "Llama and Mixtral at high speed", "Real-time applications with governance", "Cost tracking for high-throughput usage", "Low-latency enterprise AI"], ["Connect Groq API credentials", "Select models optimized for speed", "Configure guardrails for fast inference", "Monitor throughput and costs"]),
    // Identity (4)
    ig("okta", "Okta SSO", "identity", "Integrate Remova with Okta for seamless single sign-on. Employees access governed AI using their existing Okta credentials with automatic provisioning.", ["SAML 2.0 and OIDC support", "Automatic user provisioning", "Group-based department mapping", "MFA enforcement", "Instant access revocation on termination"], ["Configure SAML/OIDC in Okta admin", "Map Okta groups to Remova departments", "Enable MFA requirements", "Test SSO flow and deploy"]),
    ig("azure-ad", "Microsoft Entra ID (Azure AD)", "identity", "Connect Remova to Microsoft Entra ID for enterprise SSO. Leverage existing Azure AD groups, conditional access policies, and MFA.", ["SAML 2.0 and OIDC integration", "Azure AD group synchronization", "Conditional access policy support", "MFA through Microsoft Authenticator", "Automatic user lifecycle management"], ["Register Remova in Azure AD", "Configure SAML or OIDC connection", "Map AD groups to departments", "Enable conditional access"]),
    ig("google-workspace", "Google Workspace SSO", "identity", "Integrate Remova with Google Workspace for SSO. Employees sign in with their Google credentials for instant governed AI access.", ["Google OAuth 2.0 integration", "Google Groups mapping", "Automatic user provisioning", "Google Admin console management", "Chrome browser integration"], ["Configure OAuth in Google Admin", "Map Google Groups to departments", "Enable auto-provisioning", "Deploy to organization"]),
    ig("onelogin", "OneLogin SSO", "identity", "Connect Remova to OneLogin for enterprise SSO with automated user provisioning and department mapping.", ["SAML 2.0 integration", "SCIM provisioning", "Role mapping", "MFA enforcement", "Directory integration"], ["Add Remova app in OneLogin", "Configure SAML connection", "Set up SCIM provisioning", "Map roles to departments"]),
    // Cloud (3)
    ig("aws", "Amazon Web Services (AWS)", "cloud", "Deploy Remova on AWS infrastructure for enterprise-grade reliability, compliance, and integration with your existing AWS services.", ["AWS VPC deployment", "Private link connectivity", "AWS KMS encryption", "CloudWatch monitoring integration", "AWS GovCloud support"], ["Select AWS region for deployment", "Configure VPC and security groups", "Enable KMS encryption", "Set up CloudWatch monitoring"]),
    ig("azure", "Microsoft Azure", "cloud", "Deploy Remova on Azure infrastructure. Integration with Azure services, compliance with Azure certifications, and hybrid cloud support.", ["Azure VM or AKS deployment", "Azure Key Vault integration", "Azure Monitor support", "Azure Government cloud option", "Hybrid on-prem/cloud deployment"], ["Choose Azure region", "Configure Azure networking", "Enable Key Vault encryption", "Set up Azure Monitor"]),
    ig("gcp", "Google Cloud Platform (GCP)", "cloud", "Deploy Remova on GCP. Leverage Google's infrastructure with Remova's AI governance layer for maximum performance and security.", ["GKE or Compute Engine deployment", "Cloud KMS encryption", "Cloud Monitoring integration", "VPC Service Controls", "Data residency controls"], ["Select GCP region", "Configure VPC and service controls", "Enable Cloud KMS", "Set up monitoring"]),
    // Productivity (4)
    ig("slack", "Slack", "productivity", "Bring governed AI directly into Slack. Your team can interact with AI models in channels and DMs with full PII redaction and cost controls.", ["AI chat in Slack channels and DMs", "PII redaction on all Slack AI messages", "Department budget enforcement in Slack", "Slash commands for quick AI queries", "Thread-based AI conversations"], ["Install Remova Slack app", "Configure channel permissions", "Set up PII and guardrail rules", "Deploy to your Slack workspace"]),
    ig("microsoft-teams", "Microsoft Teams", "productivity", "Integrate governed AI into Microsoft Teams. Access 300+ models directly in Teams with enterprise guardrails and cost controls.", ["AI chat in Teams channels and chats", "PII protection for all AI interactions", "Budget controls per Teams group", "Adaptive cards for rich AI responses", "Meeting summary assistance"], ["Install Remova Teams app", "Configure permissions in Teams Admin", "Map Teams groups to departments", "Enable guardrails and deploy"]),
    ig("notion", "Notion", "productivity", "Connect Remova's governed AI to your Notion workspace. AI-powered writing, summarization, and analysis with enterprise controls.", ["AI writing assistance in Notion", "Document summarization with guardrails", "Knowledge base Q&A with PII protection", "Team workspace integration", "Cost tracking per workspace"], ["Connect Notion workspace", "Configure AI capabilities", "Set usage policies and budgets", "Deploy to team"]),
    ig("confluence", "Confluence", "productivity", "Bring governed AI to Confluence for document creation, knowledge base Q&A, and content summarization with enterprise guardrails.", ["AI-assisted page creation", "Knowledge base Q&A with guardrails", "Content summarization", "Space-based access controls", "Jira integration for AI workflows"], ["Install Remova Confluence app", "Configure space permissions", "Enable AI features with guardrails", "Set up cost controls"]),
    // Security (4)
    ig("splunk", "Splunk", "security", "Stream Remova audit logs to Splunk for centralized security monitoring. Track AI usage, policy violations, and security events in your SIEM.", ["Real-time audit log streaming", "Pre-built Splunk dashboards", "Policy violation alerting", "AI usage trend analysis", "Compliance report generation"], ["Configure Splunk HEC endpoint", "Enable audit log streaming", "Import Remova dashboard templates", "Set up violation alerts"]),
    ig("datadog", "Datadog", "security", "Monitor Remova performance and security events in Datadog. AI platform observability integrated into your existing monitoring stack.", ["Metrics and traces integration", "Security event forwarding", "Custom dashboard support", "Alert integration", "APM correlation"], ["Add Datadog API credentials", "Enable metrics forwarding", "Import monitoring dashboards", "Configure alert rules"]),
    ig("sentinel", "Microsoft Sentinel", "security", "Stream Remova security events to Microsoft Sentinel. AI security monitoring in your Azure SIEM with built-in detection rules.", ["Security event streaming", "Pre-built analytics rules", "Incident correlation", "Automated response playbooks", "Compliance workbooks"], ["Configure Sentinel data connector", "Enable event streaming", "Import analytics rules", "Set up automated responses"]),
    ig("crowdstrike", "CrowdStrike", "security", "Integrate Remova with CrowdStrike for comprehensive AI threat detection. Correlate AI security events with endpoint and identity data.", ["AI threat event forwarding", "Endpoint correlation", "Identity threat integration", "Unified security posture", "Automated containment"], ["Configure API integration", "Enable event forwarding", "Set up correlation rules", "Define containment actions"]),
    // Dev Tools (3)
    ig("github", "GitHub", "dev-tools", "Governed AI for GitHub workflows. Code review assistance, PR summarization, and documentation generation with source code protection.", ["AI-powered code review", "PR summarization with guardrails", "Documentation generation", "Source code DLP protection", "Repository-level access controls"], ["Install Remova GitHub App", "Configure repository access", "Enable code DLP rules", "Set up team budgets"]),
    ig("jira", "Jira", "dev-tools", "Bring governed AI to Jira for ticket management, sprint planning, and technical writing with enterprise guardrails.", ["AI ticket creation and triage", "Sprint planning assistance", "Technical spec generation", "Project-level access controls", "Cost tracking per project"], ["Install Remova Jira app", "Configure project permissions", "Enable AI features", "Set project budgets"]),
    ig("vscode", "VS Code", "dev-tools", "Governed AI coding assistance directly in VS Code. Multi-model code completion and chat with source code protection.", ["Multi-model code completion", "In-editor AI chat", "Source code DLP enforcement", "Configurable model selection", "Usage tracking per developer"], ["Install Remova VS Code extension", "Sign in with SSO", "Configure model preferences", "Start coding with governance"]),
];
