import { generatedModels, generatedModelsLastUpdated } from "./models.generated";

export interface ModelEntry {
    id: string;
    name: string;
    provider: string;
    releasedAt: string;
    contextLength: number;
    inputPer1M: number;
    outputPer1M: number;
    summary: string;
    description?: string;
    bestFor: string[];
    modality?: string;
    inputModalities?: string[];
    outputModalities?: string[];
    supportedParameters?: string[];
}

const featuredModels: ModelEntry[] = [
    {
        id: "deepseek/deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        provider: "DeepSeek",
        releasedAt: "2026-04-10",
        contextLength: 1048576,
        inputPer1M: 0.435,
        outputPer1M: 0.87,
        summary: "DeepSeek's next-generation flagship. Unprecedented frontier reasoning with a 1M context window and agentic control.",
        bestFor: ["Deep reasoning", "Enterprise agent orchestration", "Complex mathematics"],
    },
    {
        id: "deepseek/deepseek-v4-flash",
        name: "DeepSeek V4 Flash",
        provider: "DeepSeek",
        releasedAt: "2026-04-10",
        contextLength: 1048576,
        inputPer1M: 0.14,
        outputPer1M: 0.28,
        summary: "Ultra-fast variant of V4 for high-throughput, latency-sensitive enterprise automation.",
        bestFor: ["High-volume data processing", "Real-time agents", "Cost-effective routing"],
    },
    {
        id: "openai/gpt-5.5-pro",
        name: "GPT-5.5 Pro",
        provider: "OpenAI",
        releasedAt: "2026-03-25",
        contextLength: 1050000,
        inputPer1M: 30.0,
        outputPer1M: 180.0,
        summary: "OpenAI's most capable model to date. Engineered for the hardest algorithmic challenges and high-stakes reasoning.",
        bestFor: ["High-stakes outputs", "Algorithmic design", "Strategic decision-making"],
    },
    {
        id: "openai/gpt-5.5",
        name: "GPT-5.5",
        provider: "OpenAI",
        releasedAt: "2026-03-25",
        contextLength: 1050000,
        inputPer1M: 5.0,
        outputPer1M: 30.0,
        summary: "Standard GPT-5.5 model, providing deep capabilities and agentic tool use for the enterprise.",
        bestFor: ["General reasoning", "Coding", "Enterprise assistants"],
    },
    {
        id: "deepseek/deepseek-r1",
        name: "DeepSeek R1",
        provider: "DeepSeek",
        releasedAt: "2025-01-20",
        contextLength: 64000,
        inputPer1M: 0.7,
        outputPer1M: 2.5,
        summary: "The open reasoning champion. Outperforms o1 on many benchmarks at a fraction of the cost.",
        bestFor: ["Deep reasoning", "Mathematics", "Complex coding tasks"],
    },
    {
        id: "deepseek/deepseek-chat",
        name: "DeepSeek V3",
        provider: "DeepSeek",
        releasedAt: "2024-12-25",
        contextLength: 163840,
        inputPer1M: 0.32,
        outputPer1M: 0.89,
        summary: "Flagship mixture-of-experts model balancing top-tier reasoning with extreme cost efficiency.",
        bestFor: ["General chat", "High-volume generation", "Enterprise copilots"],
    },
    {
        id: "google/gemini-2.0-flash-001",
        name: "Gemini 2.0 Flash",
        provider: "Google",
        releasedAt: "2025-02-05",
        contextLength: 1000000,
        inputPer1M: 0.1,
        outputPer1M: 0.4,
        summary: "Incredibly fast multimodal frontier model with a massive context window.",
        bestFor: ["Multimodal tasks", "Long document analysis", "Agent orchestration"],
    },
    {
        id: "openai/o3-mini-high",
        name: "o3 Mini High",
        provider: "OpenAI",
        releasedAt: "2025-01-31",
        contextLength: 200000,
        inputPer1M: 1.1,
        outputPer1M: 4.4,
        summary: "OpenAI's fastest and most cost-effective reasoning model with high effort scaling.",
        bestFor: ["Coding agents", "STEM reasoning", "Fast multi-step planning"],
    },
    {
        id: "meta-llama/llama-3.3-70b-instruct",
        name: "Llama 3.3 70B Instruct",
        provider: "Meta",
        releasedAt: "2024-12-06",
        contextLength: 131072,
        inputPer1M: 0.1,
        outputPer1M: 0.32,
        summary: "Open-weights powerhouse delivering GPT-4 class performance efficiently.",
        bestFor: ["On-premise deployment", "Instruction following", "Cost-sensitive workloads"],
    },

    {
        id: "anthropic/claude-opus-4.6-fast",
        name: "Claude Opus 4.6 Fast",
        provider: "Anthropic",
        releasedAt: "2026-04-07",
        contextLength: 1000000,
        inputPer1M: 25,
        outputPer1M: 125,
        summary: "Fast-mode Opus 4.6 variant for higher throughput on the same frontier capability.",
        bestFor: ["High-throughput coding", "Security research", "Agent workflows"],
    },
    {
        id: "google/gemma-4-26b-a4b-it",
        name: "Gemma 4 26B A4B IT",
        provider: "Google",
        releasedAt: "2026-04-03",
        contextLength: 262144,
        inputPer1M: 0.13,
        outputPer1M: 0.4,
        summary: "Efficient multimodal MoE model tuned for reasoning, coding, and high-throughput enterprise workloads.",
        bestFor: ["Multimodal reasoning", "Cost-aware automation", "Function-calling workflows"],
    },
    {
        id: "google/gemma-4-31b-it",
        name: "Gemma 4 31B IT",
        provider: "Google",
        releasedAt: "2026-04-02",
        contextLength: 262144,
        inputPer1M: 0.14,
        outputPer1M: 0.4,
        summary: "Dense multimodal model with strong coding and document reasoning at balanced enterprise pricing.",
        bestFor: ["Coding assistants", "Document analysis", "Multilingual enterprise copilots"],
    },
    {
        id: "z-ai/glm-5.1",
        name: "GLM 5.1",
        provider: "Z.ai",
        releasedAt: "2026-04-07",
        contextLength: 202752,
        inputPer1M: 1.26,
        outputPer1M: 3.96,
        summary: "Open model built for long-horizon coding and continuously running technical workflows.",
        bestFor: ["Long-horizon coding", "Agentic workflows", "Technical reasoning"],
    },
    {
        id: "qwen/qwen3.6-plus",
        name: "Qwen3.6 Plus",
        provider: "Qwen",
        releasedAt: "2026-04-02",
        contextLength: 1000000,
        inputPer1M: 0.33,
        outputPer1M: 1.95,
        summary: "Hybrid attention and sparse MoE model for scalable multimodal reasoning at high volume.",
        bestFor: ["Multimodal workflows", "Long-context analysis", "High-volume assistants"],
    },
    {
        id: "z-ai/glm-5v-turbo",
        name: "GLM 5V Turbo",
        provider: "Z.ai",
        releasedAt: "2026-04-01",
        contextLength: 202752,
        inputPer1M: 1.2,
        outputPer1M: 4,
        summary: "Multimodal agent model designed for vision-heavy reasoning, planning, and execution loops.",
        bestFor: ["Vision-centric agents", "Complex automation", "Long-horizon planning"],
    },
    {
        id: "arcee-ai/trinity-large-thinking",
        name: "Trinity Large Thinking",
        provider: "Arcee AI",
        releasedAt: "2026-04-01",
        contextLength: 262144,
        inputPer1M: 0.22,
        outputPer1M: 0.85,
        summary: "Open reasoning model optimized for agentic and benchmark-heavy analytical workloads.",
        bestFor: ["Reasoning tasks", "Agent workflows", "Cost-efficient open deployment"],
    },
    {
        id: "x-ai/grok-4.20-multi-agent",
        name: "Grok 4.20 Multi-Agent",
        provider: "xAI",
        releasedAt: "2026-03-31",
        contextLength: 2000000,
        inputPer1M: 2,
        outputPer1M: 6,
        summary: "Stable multi-agent flagship for deep research, parallel tool use, and structured synthesis.",
        bestFor: ["Deep research", "Parallel-agent tasks", "Complex synthesis"],
    },
    {
        id: "x-ai/grok-4.20",
        name: "Grok 4.20",
        provider: "xAI",
        releasedAt: "2026-03-31",
        contextLength: 2000000,
        inputPer1M: 2,
        outputPer1M: 6,
        summary: "Stable flagship optimized for fast reasoning, strong tool-calling, and long-context use.",
        bestFor: ["General reasoning", "Fast responses", "Long-context tasks"],
    },
    {
        id: "kwaipilot/kat-coder-pro-v2",
        name: "KAT-Coder-Pro V2",
        provider: "Kwaipilot",
        releasedAt: "2026-03-27",
        contextLength: 256000,
        inputPer1M: 0.3,
        outputPer1M: 1.2,
        summary: "Coding-focused model for enterprise software workflows and multi-system engineering tasks.",
        bestFor: ["Enterprise coding", "SaaS integration", "Developer agents"],
    },
    {
        id: "rekaai/reka-edge",
        name: "Reka Edge",
        provider: "RekaAI",
        releasedAt: "2026-03-20",
        contextLength: 16384,
        inputPer1M: 0.1,
        outputPer1M: 0.1,
        summary: "Compact multimodal model tuned for efficient visual reasoning and fast production throughput.",
        bestFor: ["Vision-language tasks", "High-volume multimodal workflows", "Low-cost assistants"],
    },
    {
        id: "nvidia/nemotron-3-super-120b-a12b",
        name: "Nemotron 3 Super 120B-A12B",
        provider: "NVIDIA",
        releasedAt: "2026-03-11",
        contextLength: 262144,
        inputPer1M: 0.1,
        outputPer1M: 0.5,
        summary: "Open hybrid MoE model designed for strong multi-agent reasoning with efficient token economics.",
        bestFor: ["Agent workflows", "Technical reasoning", "Cost-aware enterprise copilots"],
    },
    {
        id: "x-ai/grok-4.20-multi-agent-beta",
        name: "Grok 4.20 Multi-Agent Beta",
        provider: "xAI",
        releasedAt: "2026-03-12",
        contextLength: 2000000,
        inputPer1M: 2,
        outputPer1M: 6,
        summary: "Multi-agent variant designed for coordinated research and tool-heavy workflows.",
        bestFor: ["Deep research", "Parallel-agent tasks", "Complex synthesis"],
    },
    {
        id: "x-ai/grok-4.20-beta",
        name: "Grok 4.20 Beta",
        provider: "xAI",
        releasedAt: "2026-03-12",
        contextLength: 2000000,
        inputPer1M: 2,
        outputPer1M: 6,
        summary: "General flagship model optimized for fast reasoning and broad agentic use.",
        bestFor: ["General reasoning", "Fast responses", "Long-context tasks"],
    },
    {
        id: "bytedance-seed/seed-2.0-lite",
        name: "Seed-2.0-Lite",
        provider: "ByteDance",
        releasedAt: "2026-03-10",
        contextLength: 262144,
        inputPer1M: 0.25,
        outputPer1M: 2,
        summary: "Cost-efficient enterprise model with balanced multimodal and agent capabilities.",
        bestFor: ["Cost-sensitive production", "General assistants", "High-volume tasks"],
    },
    {
        id: "qwen/qwen3.5-9b",
        name: "Qwen3.5-9B",
        provider: "Qwen",
        releasedAt: "2026-03-10",
        contextLength: 256000,
        inputPer1M: 0.05,
        outputPer1M: 0.15,
        summary: "Compact, efficient model aimed at practical reasoning and coding workloads.",
        bestFor: ["Low-cost inference", "Developer tooling", "Edge-friendly workloads"],
    },
    {
        id: "openai/gpt-5.4-pro",
        name: "GPT-5.4 Pro",
        provider: "OpenAI",
        releasedAt: "2026-03-05",
        contextLength: 1050000,
        inputPer1M: 30,
        outputPer1M: 180,
        summary: "Highest-capability option for demanding reasoning, coding, and strategic tasks.",
        bestFor: ["Hard reasoning", "High-stakes outputs", "Advanced coding agents"],
    },
    {
        id: "openai/gpt-5.4",
        name: "GPT-5.4",
        provider: "OpenAI",
        releasedAt: "2026-03-05",
        contextLength: 1050000,
        inputPer1M: 2.5,
        outputPer1M: 15,
        summary: "Frontier model for strong reasoning and broad enterprise use with very long context.",
        bestFor: ["Enterprise copilots", "Long documents", "Cross-functional workflows"],
    },
    {
        id: "inception/mercury-2",
        name: "Mercury 2",
        provider: "Inception",
        releasedAt: "2026-03-04",
        contextLength: 128000,
        inputPer1M: 0.25,
        outputPer1M: 0.75,
        summary: "Reasoning-focused model tuned for low-latency output and iterative problem solving.",
        bestFor: ["Latency-sensitive UX", "Reasoning at scale", "Interactive assistants"],
    },
    {
        id: "openai/gpt-5.3-chat",
        name: "GPT-5.3 Chat",
        provider: "OpenAI",
        releasedAt: "2026-03-03",
        contextLength: 128000,
        inputPer1M: 1.75,
        outputPer1M: 14,
        summary: "High-quality conversational model optimized for day-to-day enterprise assistants.",
        bestFor: ["General chat", "Team assistants", "Knowledge workflows"],
    },
    {
        id: "google/gemini-3.1-flash-lite-preview",
        name: "Gemini 3.1 Flash Lite Preview",
        provider: "Google",
        releasedAt: "2026-03-03",
        contextLength: 1048576,
        inputPer1M: 0.25,
        outputPer1M: 1.5,
        summary: "Efficiency-first model targeting high-throughput enterprise workloads.",
        bestFor: ["Batch processing", "Large-scale automation", "High request volume"],
    },
    {
        id: "qwen/qwen3.5-flash-02-23",
        name: "Qwen3.5-Flash",
        provider: "Qwen",
        releasedAt: "2026-02-25",
        contextLength: 1000000,
        inputPer1M: 0.1,
        outputPer1M: 0.4,
        summary: "High-context flash model balancing speed, quality, and strong cost efficiency.",
        bestFor: ["Long-context analysis", "Cost-aware assistants", "Operational automation"],
    },
    {
        id: "qwen/qwen3.5-122b-a10b",
        name: "Qwen3.5-122B-A10B",
        provider: "Qwen",
        releasedAt: "2026-02-25",
        contextLength: 262144,
        inputPer1M: 0.26,
        outputPer1M: 2.08,
        summary: "Large-capacity reasoning model for high-quality outputs across complex domains.",
        bestFor: ["Technical analysis", "Advanced reasoning", "Multimodal-heavy tasks"],
    },
    {
        id: "google/gemini-3.1-pro-preview-customtools",
        name: "Gemini 3.1 Pro Preview Custom Tools",
        provider: "Google",
        releasedAt: "2026-02-25",
        contextLength: 1048576,
        inputPer1M: 2,
        outputPer1M: 12,
        summary: "Tool-call optimized variant for reliable orchestration in agentic systems.",
        bestFor: ["Tool calling", "Structured workflows", "Agent orchestration"],
    },
    {
        id: "openai/gpt-5.3-codex",
        name: "GPT-5.3-Codex",
        provider: "OpenAI",
        releasedAt: "2026-02-24",
        contextLength: 400000,
        inputPer1M: 1.75,
        outputPer1M: 14,
        summary: "Coding-focused model optimized for software design, implementation, and refactoring.",
        bestFor: ["Code generation", "Code review", "Agentic software tasks"],
    },
    {
        id: "google/gemini-3.1-pro-preview",
        name: "Gemini 3.1 Pro Preview",
        provider: "Google",
        releasedAt: "2026-02-19",
        contextLength: 1048576,
        inputPer1M: 2,
        outputPer1M: 12,
        summary: "Frontier reasoning model for demanding decision support and production copilots.",
        bestFor: ["Complex reasoning", "Enterprise copilots", "Long-context planning"],
    },
    {
        id: "anthropic/claude-sonnet-4.6",
        name: "Claude Sonnet 4.6",
        provider: "Anthropic",
        releasedAt: "2026-02-17",
        contextLength: 1000000,
        inputPer1M: 3,
        outputPer1M: 15,
        summary: "Balanced high-performance model for coding, agents, and professional writing.",
        bestFor: ["Engineering teams", "Knowledge work", "Agent-assisted operations"],
    },
    {
        id: "minimax/minimax-m2.5",
        name: "MiniMax M2.5",
        provider: "MiniMax",
        releasedAt: "2026-02-12",
        contextLength: 196608,
        inputPer1M: 0.25,
        outputPer1M: 1.2,
        summary: "General-purpose production model focused on practical productivity workflows.",
        bestFor: ["Operational assistants", "General chat", "Cost-aware deployment"],
    },
    {
        id: "z-ai/glm-5",
        name: "GLM 5",
        provider: "Z.ai",
        releasedAt: "2026-02-11",
        contextLength: 202752,
        inputPer1M: 0.72,
        outputPer1M: 2.3,
        summary: "Open flagship model targeting strong reasoning and long-horizon agent workflows.",
        bestFor: ["Planning-heavy tasks", "Complex automation", "Open-model strategies"],
    },
    {
        id: "anthropic/claude-opus-4.6",
        name: "Claude Opus 4.6",
        provider: "Anthropic",
        releasedAt: "2026-02-04",
        contextLength: 1000000,
        inputPer1M: 5,
        outputPer1M: 25,
        summary: "Top-tier capability model for complex enterprise reasoning and deep analysis.",
        bestFor: ["Strategic analysis", "Complex writing", "Long reasoning chains"],
    },
];

const mergedModels = new Map<string, ModelEntry>();

for (const model of featuredModels) {
    mergedModels.set(model.id, model);
}

for (const model of generatedModels as ModelEntry[]) {
    if (!mergedModels.has(model.id)) {
        mergedModels.set(model.id, model);
    }
}

export const models: ModelEntry[] = Array.from(mergedModels.values()).sort((a, b) => {
    const dateComparison = b.releasedAt.localeCompare(a.releasedAt);
    if (dateComparison !== 0) return dateComparison;
    return a.name.localeCompare(b.name);
});

const latestFeaturedRelease = featuredModels.reduce(
    (latest, model) => (model.releasedAt > latest ? model.releasedAt : latest),
    "0000-00-00"
);

export const modelsLastUpdated =
    latestFeaturedRelease > generatedModelsLastUpdated ? latestFeaturedRelease : generatedModelsLastUpdated;
