export interface UseCase {
    slug: string;
    category: "industry" | "role" | "function";
    metaTitle: string;
    metaDescription: string;
    headline: string;
    subheadline: string;
    description: string;
    challenges: string[];
    solutions: { title: string; description: string }[];
    faqs?: { question: string; answer: string }[];
}

export const useCases: UseCase[] = [
    {
        slug: "financial-services",
        category: "industry",
        metaTitle: "AI Governance for Financial Services | Remova",
        metaDescription: "Govern AI usage in financial organizations with policy controls, auditability, and spend management.",
        headline: "AI for Financial Services",
        subheadline: "Control risk while teams use AI productively",
        description: "Financial teams need controlled AI adoption across operations, analysis, and client workflows while maintaining strong governance.",
        challenges: [
            "Sensitive financial data handling",
            "Auditability requirements",
            "Cross-team policy consistency",
            "Cost predictability",
            "Role-scoped access",
        ],
        solutions: [
            { title: "Sensitive Data Protection", description: "Apply configurable protection controls to reduce accidental data exposure." },
            { title: "Audit Trails", description: "Maintain traceable records for review and governance reporting." },
            { title: "Department Budgets", description: "Set spending limits and alerts by team." },
            { title: "Role-Based Access", description: "Scope access and controls by organizational role." },
        ],
    },
    {
        slug: "healthcare",
        category: "industry",
        metaTitle: "AI Governance for Healthcare Organizations | Remova",
        metaDescription: "Deploy AI with governance controls for healthcare teams handling sensitive workflows and records.",
        headline: "AI for Healthcare Organizations",
        subheadline: "Enable AI usage with strong privacy and control",
        description: "Healthcare teams need AI support for documentation and operations while maintaining strict data handling and access boundaries.",
        challenges: [
            "Sensitive record handling",
            "Access controls across clinical and non-clinical roles",
            "Consistent policy enforcement",
            "Audit-ready activity records",
            "Retention governance",
        ],
        solutions: [
            { title: "Retention Controls", description: "Configure data handling behavior to match organizational policy." },
            { title: "Role-Based Access", description: "Apply scoped permissions for different job functions." },
            { title: "Policy Guardrails", description: "Enforce approved usage patterns across teams." },
            { title: "Audit Trails", description: "Support internal review and compliance workflows." },
        ],
    },
    {
        slug: "legal-services",
        category: "industry",
        metaTitle: "AI Governance for Legal Teams | Remova",
        metaDescription: "Use AI in legal workflows with controlled access, retention settings, and policy checks.",
        headline: "AI for Legal Services",
        subheadline: "Support legal work with governed AI controls",
        description: "Legal organizations need AI assistance for drafting and research while maintaining strict confidentiality and access discipline.",
        challenges: [
            "Confidential matter handling",
            "Need-to-know access boundaries",
            "Retention policy alignment",
            "Usage traceability",
            "Cross-practice consistency",
        ],
        solutions: [
            { title: "Role-Based Access", description: "Scope access by team responsibilities and governance policy." },
            { title: "Retention Controls", description: "Apply stricter data handling behavior for sensitive workflows." },
            { title: "Preset Workflows", description: "Standardize approved legal use patterns." },
            { title: "Audit Trails", description: "Maintain clear records for internal review." },
        ],
    },
    {
        slug: "technology",
        category: "industry",
        metaTitle: "AI Governance for Technology Teams | Remova",
        metaDescription: "Scale AI adoption in technology organizations with policy, cost, and access controls.",
        headline: "AI for Technology Organizations",
        subheadline: "Scale AI usage without losing governance",
        description: "Technology teams move quickly and need AI support across engineering, operations, and go-to-market functions with centralized governance.",
        challenges: [
            "Rapid tool adoption",
            "Cross-functional usage growth",
            "Policy drift between teams",
            "Cost volatility",
            "Operational governance at scale",
        ],
        solutions: [
            { title: "Model Governance", description: "Control model availability by team and policy posture." },
            { title: "Department Budgets", description: "Track and control cost by function." },
            { title: "Governed API Access", description: "Integrate AI into internal tools without bypassing policy." },
            { title: "Usage Analytics", description: "Monitor adoption, safety events, and spend in one view." },
        ],
    },
    {
        slug: "public-sector",
        category: "industry",
        metaTitle: "AI Governance for Public Sector Teams | Remova",
        metaDescription: "Support public-sector AI adoption with policy controls, oversight, and operational transparency.",
        headline: "AI for Public Sector Teams",
        subheadline: "Improve service workflows with governed AI adoption",
        description: "Public-sector teams require strong oversight and accountability when adopting AI for service delivery and internal operations.",
        challenges: [
            "High accountability standards",
            "Clear access governance",
            "Consistent policy enforcement",
            "Reporting and oversight requirements",
            "Cross-agency coordination",
        ],
        solutions: [
            { title: "Policy Guardrails", description: "Apply clear policy checks across usage scenarios." },
            { title: "Audit Trails", description: "Provide traceable records for oversight workflows." },
            { title: "Role-Based Access", description: "Limit access by organizational responsibility." },
            { title: "Usage Analytics", description: "Track rollout health and control effectiveness." },
        ],
    },
    {
        slug: "ciso",
        category: "role",
        metaTitle: "AI Governance for Security Leaders | Remova",
        metaDescription: "Give security leaders practical controls for AI policy enforcement, monitoring, and incident response.",
        headline: "AI Governance for Security Leaders",
        subheadline: "Enable adoption with enforceable controls",
        description: "Security leaders need confidence that AI can be adopted with protection controls, clear visibility, and accountable ownership.",
        challenges: [
            "Unmanaged team usage",
            "Sensitive data exposure risk",
            "Inconsistent policy enforcement",
            "Limited operational visibility",
            "Incident response readiness",
        ],
        solutions: [
            { title: "Sensitive Data Protection", description: "Reduce accidental data exposure in prompts and outputs." },
            { title: "Policy Guardrails", description: "Enforce security and usage policy in real time." },
            { title: "Audit Trails", description: "Improve investigation and review capability." },
            { title: "Usage Analytics", description: "Track patterns and high-risk activity signals." },
        ],
    },
    {
        slug: "cio",
        category: "role",
        metaTitle: "AI Governance for IT Leadership | Remova",
        metaDescription: "Support enterprise AI rollout with governance, budget control, and team-level access management.",
        headline: "AI Governance for IT Leadership",
        subheadline: "Roll out AI in a controlled, scalable way",
        description: "IT leaders need a repeatable way to launch AI across teams without creating unmanaged risk or spend.",
        challenges: [
            "Cross-team rollout complexity",
            "Governance consistency",
            "Access management overhead",
            "Budget accountability",
            "Adoption tracking",
        ],
        solutions: [
            { title: "Onboarding Controls", description: "Launch new teams with governance defaults." },
            { title: "Role-Based Access", description: "Delegate administration safely." },
            { title: "Department Budgets", description: "Control spend with team-level limits." },
            { title: "Usage Analytics", description: "Track adoption and operational performance." },
        ],
    },
    {
        slug: "compliance-lead",
        category: "role",
        metaTitle: "AI Governance for Compliance Teams | Remova",
        metaDescription: "Help compliance teams monitor policy adherence with audit trails and governance analytics.",
        headline: "AI Governance for Compliance Teams",
        subheadline: "Turn policy into visible operational controls",
        description: "Compliance teams need practical controls and evidence to monitor AI usage policy and support internal review cycles.",
        challenges: [
            "Policy-to-practice gaps",
            "Evidence collection overhead",
            "Inconsistent controls across departments",
            "Limited visibility into exceptions",
            "Reporting complexity",
        ],
        solutions: [
            { title: "Audit Trails", description: "Capture relevant records for review and reporting." },
            { title: "Policy Guardrails", description: "Reduce manual policy enforcement workload." },
            { title: "Retention Controls", description: "Align data handling with compliance posture." },
            { title: "Usage Analytics", description: "Monitor policy adherence trends over time." },
        ],
    },
    {
        slug: "department-manager",
        category: "role",
        metaTitle: "AI Governance for Department Managers | Remova",
        metaDescription: "Give department managers practical controls for budgets, access, and approved AI workflows.",
        headline: "AI Governance for Department Managers",
        subheadline: "Enable your team with clear guardrails",
        description: "Department managers need fast team enablement with clear policy boundaries and budget accountability.",
        challenges: [
            "Balancing speed and control",
            "Managing team spend",
            "Onboarding new users",
            "Keeping workflows consistent",
            "Escalating policy exceptions",
        ],
        solutions: [
            { title: "Department Budgets", description: "Set clear limits and alerts for team usage." },
            { title: "Preset Workflows", description: "Standardize team tasks with approved defaults." },
            { title: "Role-Based Access", description: "Delegate team administration without over-permissioning." },
            { title: "Usage Analytics", description: "Review team trends and adjust controls as needed." },
        ],
    },
    {
        slug: "policy-enforcement",
        category: "function",
        metaTitle: "AI Policy Enforcement | Remova",
        metaDescription: "Apply enforceable AI policy controls across teams through centralized governance.",
        headline: "AI Policy Enforcement",
        subheadline: "Move from written policy to operational controls",
        description: "Organizations can translate policy into active controls for daily AI usage across departments.",
        challenges: [
            "Written policy without enforcement",
            "Manual review burden",
            "Inconsistent control application",
            "Delayed risk detection",
            "Limited policy feedback loops",
        ],
        solutions: [
            { title: "Policy Guardrails", description: "Apply rule-based and contextual checks in workflows." },
            { title: "Sensitive Data Protection", description: "Reduce accidental disclosures during AI usage." },
            { title: "Audit Trails", description: "Track how policy is applied over time." },
            { title: "Usage Analytics", description: "Use data to tune policy controls." },
        ],
    },
    {
        slug: "cost-governance",
        category: "function",
        metaTitle: "AI Cost Governance | Remova",
        metaDescription: "Control AI spend through budgeting, allocation, and team-level usage visibility.",
        headline: "AI Cost Governance",
        subheadline: "Keep AI spend aligned with business priorities",
        description: "Cost governance helps finance and operations teams scale AI usage without losing financial control.",
        challenges: [
            "Unclear spend ownership",
            "Budget overruns",
            "Limited team-level visibility",
            "Late cost discovery",
            "Difficult forecasting",
        ],
        solutions: [
            { title: "Department Budgets", description: "Assign and enforce team-level spending boundaries." },
            { title: "Usage Analytics", description: "Track spend trends and budget utilization." },
            { title: "Model Governance", description: "Align model availability with cost posture." },
            { title: "Onboarding Controls", description: "Apply budget defaults during team rollout." },
        ],
    },
    {
        slug: "safe-ai-chat",
        category: "function",
        metaTitle: "Safe Enterprise AI Chat | Remova",
        metaDescription: "Deploy an enterprise AI chat experience with policy, privacy, and budget controls built in.",
        headline: "Safe Enterprise AI Chat",
        subheadline: "Give teams AI access with governance from day one",
        description: "Organizations can provide AI chat capabilities while preserving policy controls, access boundaries, and spend governance.",
        challenges: [
            "Need for broad team adoption",
            "Safety and policy requirements",
            "Sensitive content handling",
            "Cost oversight",
            "Operational consistency",
        ],
        solutions: [
            { title: "Policy Guardrails", description: "Apply policy checks to daily chat usage." },
            { title: "Sensitive Data Protection", description: "Protect confidential content in prompts and responses." },
            { title: "Department Budgets", description: "Control spend by team with alerts and limits." },
            { title: "Role-Based Access", description: "Manage who can access what capabilities." },
        ],
    },
];
