const legacyBlogSlugs = [
    "why-ai-governance-matters-2026",
    "shadow-ai-enterprise-risk",
    "ai-cost-management-guide",
    "pii-redaction-best-practices",
    "eu-ai-act-compliance-guide",
    "building-ai-governance-program",
    "ai-guardrails-implementation",
    "zero-history-architecture-explained",
    "ai-for-regulated-industries",
    "multi-model-strategy-enterprise",
    "prompt-injection-prevention",
    "department-ai-budgets",
    "hipaa-compliant-ai-deployment",
    "soc2-ai-governance",
    "responsible-ai-framework",
    "ai-security-threat-landscape",
    "llm-evaluation-enterprise",
    "ai-onboarding-employees",
    "ai-roi-measurement",
    "gdpr-ai-compliance",
    "nist-ai-rmf-guide",
    "ai-vendor-evaluation-checklist",
    "ai-chatbot-vs-ai-platform",
    "ai-model-routing-strategies",
    "comparison-ai-governance-frameworks",
    "enterprise-ai-security-architecture",
    "ai-content-creation-enterprise",
    "cost-of-ai-data-breach",
    "ai-for-customer-service",
    "ai-bias-detection-guide",
    "air-gapped-ai-deployment",
    "ai-audit-trail-best-practices",
    "future-of-enterprise-ai-2026",
    "choosing-right-ai-models",
    "ai-integration-strategies",
    "ciso-guide-ai-adoption",
    "ai-knowledge-base-setup",
    "ai-compliance-dashboard",
    "enterprise-ai-mistakes",
    "api-key-protection-ai",
    "iso-27001-ai-controls",
    "zero-trust-ai-security",
    "ai-incident-response-plan",
    "penetration-testing-ai",
    "encryption-ai-data",
    "data-classification-ai",
    "insider-threat-ai",
    "supply-chain-ai-risk",
    "cyber-insurance-ai",
    "mfa-ai-access",
    "ai-access-review",
    "ai-security-monitoring",
    "ccpa-ai-compliance",
    "ai-privacy-impact",
    "intellectual-property-ai",
    "ai-whistleblower-protection",
    "quantum-computing-ai-security",
    "ai-deepfake-enterprise",
    "social-engineering-ai",
    "ai-change-management",
    "ai-center-of-excellence",
    "measuring-ai-productivity",
    "ai-training-program-design",
    "ai-champion-program",
    "ai-it-service-management",
    "managing-multiple-ai-vendors",
    "ai-organizational-structure",
    "ai-executive-reporting",
    "ai-maturity-model",
    "ai-disaster-recovery",
    "ai-capacity-planning",
    "ai-performance-benchmarking",
    "ai-user-feedback-loops",
    "ai-procurement-guide",
    "ai-service-level-agreements",
    "ai-total-cost-ownership",
    "ai-cross-functional-teams",
    "ai-innovation-governance-balance",
    "ai-technical-debt",
    "ai-insurance-industry",
    "ai-pharmaceutical",
    "ai-real-estate",
    "ai-telecommunications",
    "ai-energy-utilities",
    "ai-construction",
    "ai-agriculture",
    "ai-hospitality",
    "ai-media-entertainment",
    "ai-transportation",
    "ai-nonprofit",
    "ai-consulting-firms",
    "ai-accounting-firms",
    "ai-private-equity",
    "ai-venture-capital",
    "ai-supply-chain",
    "ai-cybersecurity-teams",
    "ai-data-analytics-teams",
    "ai-product-management",
    "ai-executive-assistants",
    "rag-architecture-guide",
    "vector-database-comparison",
    "ai-observability-guide",
    "fine-tuning-vs-rag",
    "ai-testing-strategies",
    "prompt-engineering-enterprise",
    "ai-caching-strategies",
    "token-optimization-guide",
    "ai-api-rate-limiting",
    "multimodal-ai-enterprise",
    "ai-streaming-architecture",
    "ai-function-calling-guide",
    "ai-memory-systems",
    "ai-model-failover",
    "structured-outputs-ai",
    "ai-batch-processing",
    "ai-webhook-integration",
    "ai-sdk-comparison",
    "kubernetes-ai-deployment",
    "ai-logging-best-practices",
    "state-of-enterprise-ai-2026",
    "ai-regulation-global-tracker",
    "enterprise-ai-spending-analysis",
    "ai-talent-market-2026",
    "open-source-vs-proprietary-models",
    "ai-market-consolidation",
    "small-language-models",
    "ai-sustainability-enterprise",
    "ai-worker-displacement",
    "generative-ai-vs-predictive-ai",
    "ai-copilot-comparison",
    "ai-in-boardroom",
    "ai-digital-transformation",
    "multicloud-ai-strategy",
    "ai-data-mesh-integration",
    "ai-edge-computing",
    "ai-blockchain-identity",
    "conversational-ai-enterprise",
    "ai-automated-testing",
    "ai-personalization-privacy",
    "ai-agent-governance",
    "agentic-ai-security",
    "ai-reasoning-models",
    "ai-code-generation-governance",
    "ai-synthetic-data-generation",
    "differential-privacy-ai",
    "federated-learning-enterprise",
    "ai-model-governance-lifecycle",
    "ai-ethics-committee-guide",
    "sovereign-ai-movement",
    "ai-explainability-enterprise",
    "ai-watermarking-detection",
    "confidential-computing-ai",
    "ai-digital-twins-governance",
    "autonomous-ai-decision-making",
    "ai-organizational-learning",
    "ai-competitive-intelligence",
    "ai-crisis-communication",
    "ai-vendor-lock-in-escape",
    "future-proofing-ai-governance",
    "ai-value-chain-analysis",
    "ai-platform-migration-guide",
    "ai-accessibility-enterprise",
    "end-to-end-ai-governance",
    "ai-governance-roi-study",
    "ai-partnership-models",
    "enterprise-ai-2028-vision",
    "ai-ethics-case-studies",
    "building-ai-trust",
    "ai-governance-maturity-assessment",
] as const;

export const legacyResourceSlugs = [
    "ai-governance-starter-kit",
    "enterprise-ai-security-checklist",
    "ai-vendor-evaluation-scorecard",
    "hipaa-ai-compliance-guide",
    "gdpr-ai-compliance-template",
    "ai-budget-planning-worksheet",
    "ai-acceptable-use-policy",
    "nist-ai-rmf-mapping-guide",
    "eu-ai-act-readiness-assessment",
    "ai-incident-response-playbook",
    "soc2-ai-controls-mapping",
    "ai-training-curriculum",
    "ai-roi-calculator",
    "ai-policy-communication-kit",
    "ai-maturity-assessment-tool",
    "comparison-matrix-ai-platforms",
    "quarterly-ai-review-template",
    "ai-risk-register-template",
    "ai-governance-kpi-dashboard",
    "ai-deployment-runbook",
    "prompt-library-enterprise",
    "ai-security-architecture-blueprint",
    "ai-ethics-framework-template",
    "data-sovereignty-playbook",
] as const;

const legacyBlogSlugSet = new Set<string>(legacyBlogSlugs);
const legacyResourceSlugSet = new Set<string>(legacyResourceSlugs);

const legacyBlogRedirectTargets: Record<string, string> = {
    "ai-cost-management-guide": "/blog/ai-cost-management-finops-guide",
    "eu-ai-act-compliance-guide": "/blog/eu-ai-act-enterprise-readiness-checklist",
    "ai-center-of-excellence": "/use-cases/ai-center-of-excellence",
    "end-to-end-ai-governance": "/blog/what-is-enterprise-ai-governance-2026-guide",
    "department-ai-budgets": "/features/department-budgets",
    "prompt-injection-prevention": "/glossary/prompt-injection",
    "hipaa-compliant-ai-deployment": "/use-cases/healthcare",
    "ai-incident-response-plan": "/blog/ai-incident-response-sensitive-data-llm",
    "ai-vendor-evaluation-checklist": "/blog/ai-vendor-risk-management-llm-tools",
    "enterprise-ai-security-architecture": "/blog/enterprise-ai-security-ciso-playbook",
    "ai-product-management": "/blog",
};

const legacyResourceRedirectTargets: Record<string, string> = {
    "ai-acceptable-use-policy": "/blog/ai-acceptable-use-policy-template",
    "eu-ai-act-readiness-assessment": "/blog/eu-ai-act-readiness-checklist-generative-ai",
    "ai-incident-response-playbook": "/blog/ai-incident-response-sensitive-data-llm",
    "ai-security-architecture-blueprint": "/blog/enterprise-ai-security-ciso-playbook",
    "ai-vendor-evaluation-scorecard": "/blog/ai-vendor-risk-management-llm-tools",
};

export const legacyBlogStaticParams = legacyBlogSlugs.map((slug) => ({ slug }));
export const legacyResourceStaticParams = legacyResourceSlugs.map((slug) => ({ slug }));

export function getLegacyBlogRedirect(slug: string): string | undefined {
    if (!legacyBlogSlugSet.has(slug)) return undefined;
    return legacyBlogRedirectTargets[slug] ?? "/blog";
}

export function getLegacyResourceRedirect(slug: string): string | undefined {
    if (!legacyResourceSlugSet.has(slug)) return undefined;
    return legacyResourceRedirectTargets[slug] ?? "/resources";
}

export function getLegacyFeatureRedirect(slug: string): string | undefined {
    if (slug === "role-based-access") return "/features/role-access-control";
    return undefined;
}
