import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import {
    getLegacyAlternativeRedirect,
    getLegacyBlogCategoryRedirect,
    getLegacyBlogRedirect,
    getLegacyCompareRedirect,
    getLegacyCustomerRedirect,
    getLegacyFeatureRedirect,
    getLegacyGlossaryRedirect,
    getLegacyIntegrationRedirect,
    getLegacyModelRedirect,
    getLegacyResourceRedirect,
    getLegacyServiceRedirect,
    getLegacyTopLevelRedirect,
    getLegacyTrustRedirect,
    getLegacyUseCaseRedirect,
    legacyAlternativeStaticParams,
    legacyBlogCategoryStaticParams,
    legacyBlogStaticParams,
    legacyCompareStaticParams,
    legacyCustomerStaticParams,
    legacyFeatureStaticParams,
    legacyGlossaryStaticParams,
    legacyIntegrationStaticParams,
    legacyModelStaticParams,
    legacyResourceStaticParams,
    legacyServiceStaticParams,
    legacyTopLevelStaticParams,
    legacyTrustStaticParams,
    legacyUseCaseStaticParams,
} from "../lib/legacy-redirects";
import { getModelLandingRedirect, modelLandingRedirectStaticParams, modelLandings } from "../content/model-landings";
import { modelVideoSlugs } from "../content/model-video-manifest.generated";
import { SITE_URL } from "../lib/seo";

type RedirectEntry = {
    from: string;
    to: string;
};

const currentModelLandingSlugs = new Set(modelLandings.map((entry) => entry.slug));

function normalizePath(path: string) {
    if (path.startsWith("http://") || path.startsWith("https://")) return path;
    return path.startsWith("/") ? path : `/${path}`;
}

function add(entries: RedirectEntry[], from: string, to: string | undefined) {
    if (!to) return;
    const normalizedFrom = normalizePath(from);
    const normalizedTo = normalizePath(to);
    if (normalizedFrom === normalizedTo) return;
    entries.push({ from: normalizedFrom, to: normalizedTo });
}

const entries: RedirectEntry[] = [];

for (const { slug } of legacyBlogStaticParams) add(entries, `/blog/${slug}`, getLegacyBlogRedirect(slug));
for (const { slug } of legacyResourceStaticParams) add(entries, `/resources/${slug}`, getLegacyResourceRedirect(slug));
for (const { slug } of legacyFeatureStaticParams) add(entries, `/features/${slug}`, getLegacyFeatureRedirect(slug));
for (const { slug } of legacyModelStaticParams) {
    if (!currentModelLandingSlugs.has(slug) && !getModelLandingRedirect(slug)) {
        add(entries, `/models/${slug}`, getLegacyModelRedirect(slug));
    }
}
for (const { slug } of legacyAlternativeStaticParams) add(entries, `/alternative/${slug}`, getLegacyAlternativeRedirect(slug));
for (const { slug } of legacyCompareStaticParams) add(entries, `/compare/${slug}`, getLegacyCompareRedirect(slug));
for (const { slug } of legacyUseCaseStaticParams) add(entries, `/use-cases/${slug}`, getLegacyUseCaseRedirect(slug));
for (const { slug } of legacyGlossaryStaticParams) add(entries, `/glossary/${slug}`, getLegacyGlossaryRedirect(slug));
for (const { slug } of legacyBlogCategoryStaticParams) add(entries, `/blog/category/${slug}`, getLegacyBlogCategoryRedirect(slug));
for (const { slug } of legacyCustomerStaticParams) add(entries, `/customers/${slug}`, getLegacyCustomerRedirect(slug));
for (const { slug } of legacyIntegrationStaticParams) add(entries, `/integrations/${slug}`, getLegacyIntegrationRedirect(slug));
for (const { slug } of legacyTrustStaticParams) add(entries, `/trust/${slug}`, getLegacyTrustRedirect(slug));
for (const { slug } of legacyServiceStaticParams) add(entries, `/services/${slug}`, getLegacyServiceRedirect(slug));
for (const { legacy } of legacyTopLevelStaticParams) add(entries, `/${legacy}`, getLegacyTopLevelRedirect(legacy));
for (const { slug } of modelLandingRedirectStaticParams) add(entries, `/models/${slug}`, getModelLandingRedirect(slug));
for (const slug of modelVideoSlugs) {
    if (!currentModelLandingSlugs.has(slug) && !getModelLandingRedirect(slug)) add(entries, `/models/${slug}`, "/models");
}

add(entries, "/affiliate", "/");
add(entries, "/help-support", "/");
add(entries, "/impact", "/");
add(entries, "/no-abuse", "/");
add(entries, "/cdn-cgi/l/email-protection", "/");
add(entries, "/demo", "/features");

const uniqueEntries = Array.from(
    new Map(entries.map((entry) => [`${entry.from}\t${entry.to}`, entry])).values()
).sort((a, b) => a.from.localeCompare(b.from));

function csvValue(value: string) {
    return `"${value.replace(/"/g, '""')}"`;
}

const redirectsText = [
    "# Generated by scripts/generate-redirects.ts",
    "# GitHub Pages ignores this file; import docs/cloudflare-redirects.csv or migrate the static build to an edge host that honors _redirects.",
    ...uniqueEntries.map((entry) => `${entry.from} ${entry.to} 301`),
    "",
].join("\n");

const cloudflareCsv = [
    "source_url,target_url,status_code",
    ...uniqueEntries.map((entry) => {
        const sourceUrl = entry.from.startsWith("http") ? entry.from : `${SITE_URL}${entry.from}`;
        const targetUrl = entry.to.startsWith("http") ? entry.to : `${SITE_URL}${entry.to}`;
        return [sourceUrl, targetUrl, "301"].map(csvValue).join(",");
    }),
    "",
].join("\n");

const outRedirectsPath = join(process.cwd(), "out", "_redirects");
const docsCsvPath = join(process.cwd(), "docs", "cloudflare-redirects.csv");

mkdirSync(dirname(outRedirectsPath), { recursive: true });
mkdirSync(dirname(docsCsvPath), { recursive: true });
writeFileSync(outRedirectsPath, redirectsText);
writeFileSync(docsCsvPath, cloudflareCsv);

console.log(`Generated ${uniqueEntries.length} redirects in out/_redirects and docs/cloudflare-redirects.csv`);
